// Presentation uses concept labels; stable record identifiers remain unchanged.
export const exampleVersion='woodworking-taxonomy-examples-1';
export const scenarios=[
['prepare-board','หาแนวอ่านก่อนไสกระดานทำชั้นวาง','ผู้เริ่มต้นมีไม้สำหรับทำชั้นวาง แต่ค้นคำว่า “กบ” แล้วได้เนื้อหาหลายชนิดปนกัน','เริ่มที่ Woodworking tool → Hand plane แล้วเปรียบเทียบ Jack plane, Jointer plane และ Smoothing plane; ลำดับขั้นการทำงานเขียนในบทความ ไม่ใช้เป็นความสัมพันธ์ is-a','High'],
['japanese-plane','ค้นเนื้อหาเรื่องกบญี่ปุ่น','ผู้อ่านเห็นคำว่า kanna ในบทความและอยากรู้ว่าเกี่ยวกับกบไสไม้ชนิดใด','เลือก Japanese hand plane ใต้ Hand plane และใช้คำเรียกจาก CV เพื่อค้นเนื้อหาที่ติดแท็กเดียวกัน','High'],
['joinery-chisel','เปรียบเทียบสิ่วก่อนเขียนเรื่องเข้าไม้','ผู้เขียนกำลังเตรียมบทความเข้าไม้ ต้องแยก Oire nomi กับ Tataki nomi ให้ผู้อ่านเห็นขอบเขต','เปิด Chisel แล้วเทียบแนวคิดลูกทั้งสองพร้อมนิยาม; ความเหมาะสมกับงานต้องมีหลักฐานเพิ่มเติมในเนื้อหา','High'],
['sharpening-guide','หาเนื้อหาการลับคม','เจ้าของจะรวบรวมบทความดูแลเครื่องมือ แต่ผลค้นปะปนหินลับกับกิจกรรมลับคม','ใช้ Maintenance → Sharpening จัดกลุ่มกิจกรรม ส่วน Sharpening stone เป็นแนวคิดเครื่องมือที่เชื่อมด้วย related ใน Thesaurus','High'],
['plane-parts','จัดบทความอธิบายส่วนประกอบกบ','ผู้เขียนจะอธิบาย Plane blade, Chipbreaker และ Plane frog โดยไม่ให้ผู้อ่านเข้าใจว่าเป็นชนิดของกบ','คงแนวคิดส่วนประกอบแยกจาก Hand plane; ความสัมพันธ์ part-of จัดใน Ontology ไม่ใส่เป็น parent แบบ is-a','Medium'],
['tool-steel','ค้นเนื้อหาวัสดุใบเครื่องมือ','ผู้อ่านต้องการอ่านเปรียบเทียบ A2 กับเหล็ก HSS แต่ไม่ต้องการรายชื่อทรัพย์สินส่วนตัว','เปิด Asset material → A2 tool steel / High-speed steel เพื่อจัดแท็กเรื่องวัสดุ โดยไม่จำแนกเหล็กเป็นชนิดของกบ','Medium']
].map(([id,label,problem,solution,priority])=>({id:'scenario-'+id,label,problem,solution,priority,owner:'เจ้าของโครงการ / ผู้เขียนเนื้อหา',status:'proposed',done:false,basis:'synthetic_fixture'}));
export function addExamples(p){if(p.taxonomyExamplesVersion===exampleVersion)return false;for(const row of scenarios)if(!p.useCases.some(x=>x.id===row.id))p.useCases.push({...row});p.taxonomyExamplesVersion=exampleVersion;return true;}
export function nameOf(p,id){const t=p.terms.find(x=>x.id===id);return t?(t.labelEn||t.labelTh||id):id;}
export function parentAllowed(p,child,parent){if(!parent)return true;const seen=new Set([child]);let todo=[parent];while(todo.length){const id=todo.pop();if(id===child)return false;if(seen.has(id))continue;seen.add(id);todo.push(...p.hierarchy.filter(e=>e.child===id).map(e=>e.parent));}return true;}
export function treeRows(p,scheme){const terms=p.terms.filter(t=>t.scheme===scheme),ids=new Set(terms.map(t=>t.id)),rows=[],visited=new Set();const priority=['asset-concept-woodworking-tool','asset-concept-chisel','asset-concept-maintenance','asset-concept-material'];const rank=id=>priority.includes(id)?priority.indexOf(id):99;const ordered=xs=>xs.sort((a,b)=>rank(a.id)-rank(b.id)||nameOf(p,a.id).localeCompare(nameOf(p,b.id)));function visit(t,depth,path){if(path.has(t.id))return;rows.push({term:t,depth});visited.add(t.id);const next=new Set([...path,t.id]);for(const child of ordered(terms.filter(c=>p.hierarchy.some(e=>e.child===c.id&&e.parent===t.id))))visit(child,depth+1,next);}for(const t of ordered(terms.filter(t=>!p.hierarchy.some(e=>e.child===t.id&&ids.has(e.parent)))))visit(t,1,new Set());for(const t of ordered(terms.filter(t=>!visited.has(t.id))))visit(t,1,new Set());return rows;}
export function mountTaxonomy(root,ctx){const {project:p,el,control,checkpoint,changed,message,rerender,checkCard,next}=ctx;const state=ctx.state;
const card=title=>{const n=el('section',undefined,'card');n.append(el('h3',title));return n;};
const mutate=fn=>{checkpoint();fn();changed();rerender();};
root.append(el('p','กำหนดการใช้งาน จัดแนวคิดจาก Controlled vocabulary ลงใน scheme และเลือก broader concept โดยความสัมพันธ์ต้องผ่าน Is-a test','taxonomy-intro'));
const banner=el('div',undefined,'card taxonomy-status');banner.append(el('span','DRAFT','badge'),el('span','โครงสร้างพร้อมแก้ไข · ความหมายและตัวอย่างยังรอเจ้าของทบทวน'));const continueButton=el('button','Continue to 4 · Thesaurus →','primary');continueButton.onclick=next;banner.append(continueButton);root.append(banner);
const cases=card('① Use cases');cases.append(el('p','ตัวอย่างสถานการณ์จำลองงานไม้ · ช่อง Done ใช้บันทึกว่าคุณได้ทดลองสถานการณ์แล้ว ไม่ใช่การรับรอง ontology','muted'));
const wrap=el('div',undefined,'table-wrap'),table=el('table',undefined,'use-case-table'),head=el('tr');for(const label of ['Use case','Problem statement','How the taxonomy solves it','Priority','Stakeholder owner','Done',''])head.append(el('th',label));table.append(head);
for(const row of p.useCases){const tr=el('tr');for(const [key,title]of Object.entries({label:'Use case',problem:'Problem statement*',solution:'How the taxonomy solves it*',priority:['High','Medium','Low'],owner:'Stakeholder owner'})){const td=el('td');td.append(control(key,title,row[key],v=>row[key]=v));tr.append(td);}const done=el('input');done.type='checkbox';done.checked=row.done===true;done.setAttribute('aria-label','Done · '+row.label);done.onchange=()=>{checkpoint();row.done=done.checked;changed();};const td=el('td');td.append(done);tr.append(td);const remove=el('button','×','danger');remove.setAttribute('aria-label','ลบ Use case · '+row.label);remove.onclick=()=>mutate(()=>p.useCases=p.useCases.filter(x=>x.id!==row.id));const removeCell=el('td');removeCell.append(remove);tr.append(removeCell);table.append(tr);}wrap.append(table);cases.append(wrap);
const newCase=el('input');newCase.placeholder='ชื่อสถานการณ์ใหม่ เช่น ค้นบทความเรื่องการไสผิวไม้';newCase.setAttribute('aria-label','Use case ใหม่');const addCase=el('button','+ Add use case');addCase.onclick=()=>{if(!newCase.value.trim())return message('กรอกชื่อสถานการณ์ก่อน');mutate(()=>p.useCases.push({id:'use-case-'+crypto.randomUUID(),label:newCase.value.trim(),problem:'',solution:'',priority:'Medium',owner:'',status:'proposed',done:false}));};const addRow=el('div',undefined,'taxonomy-add');addRow.append(newCase,addCase);cases.append(addRow);root.append(cases);
const coverage=card(''),fold=el('details');fold.open=!!state.coverage;fold.ontoggle=()=>state.coverage=fold.open;fold.append(el('summary','Coverage model · ขอบเขตที่ taxonomy ต้องครอบคลุม'));fold.append(control('coverage','What topics do we need to include?*',p.config.coverage,v=>p.config.coverage=v));const grid=el('div',undefined,'grid');grid.append(control('depth','How deep should each branch go?',p.config.depth,v=>p.config.depth=v),control('granularity','What granularity do users need?',p.config.granularity,v=>p.config.granularity=v));fold.append(grid,control('standards','Comparable organizations or standards*',p.config.standards,v=>p.config.standards=v));coverage.append(fold);root.append(coverage);
const hierarchy=card('② Schemes and hierarchy'),layout=el('div',undefined,'editor taxonomy-editor'),aside=el('aside'),detail=el('div',undefined,'concept-detail');const schemeName=el('input');schemeName.placeholder='New scheme · ชื่อกลุ่มคำ';schemeName.setAttribute('aria-label','New scheme');const addScheme=el('button','+ Add scheme');addScheme.onclick=()=>{if(!schemeName.value.trim())return message('กรอกชื่อ scheme ก่อน');mutate(()=>{const id='scheme-'+crypto.randomUUID();p.schemes.push({id,label:schemeName.value.trim(),uri:p.config.cboxNamespace+id,scope:''});state.editScheme=id;});};const addSchemeRow=el('div',undefined,'taxonomy-add');addSchemeRow.append(schemeName,addScheme);aside.append(addSchemeRow);const tree=el('div',undefined,'items taxonomy-tree');let first;
for(const scheme of p.schemes){const rows=treeRows(p,scheme.id),heading=el('div',undefined,'scheme-heading');const editScheme=el('button',scheme.label);editScheme.setAttribute('aria-label','แก้ไข scheme · '+scheme.label);editScheme.onclick=()=>{state.editScheme=scheme.id;rerender();};heading.append(editScheme,el('small',rows.length+' concepts'));tree.append(heading);for(const {term,depth}of rows){first??=term;const b=el('button',undefined,'item taxonomy-node'+(state.selected===term.id?' active':''));b.style.paddingLeft=(10+(depth-1)*18)+'px';b.append(el('span',term.labelEn||term.labelTh||term.id),el('small',depth===1?'top':'is-a · '+(p.hierarchy.find(e=>e.child===term.id)?.status||'proposed')));b.title=term.labelTh||term.labelEn;b.onclick=()=>{state.selected=term.id;rerender();};tree.append(b);}}
aside.append(tree);const unplaced=p.terms.filter(t=>!p.schemes.some(s=>s.id===t.scheme));aside.append(el('p','Unplaced terms · '+unplaced.length+' แนวคิด','muted'));for(const t of unplaced){const b=el('button',t.labelEn||t.labelTh);b.onclick=()=>{state.selected=t.id;rerender();};aside.append(b);}if(!unplaced.length)aside.append(el('span','ทุกแนวคิดมี scheme แล้ว · ยังไม่ใช่ semantic approval','badge'));
if(state.editScheme){const scheme=p.schemes.find(s=>s.id===state.editScheme);if(scheme){const editor=card('แก้ไข scheme');editor.append(control('label','ชื่อ scheme',scheme.label,v=>scheme.label=v),control('uri','Scheme URI',scheme.uri,v=>scheme.uri=v),control('scope','ขอบเขต scheme*',scheme.scope,v=>scheme.scope=v));const close=el('button','กลับไปดูแนวคิด');close.onclick=()=>{state.editScheme='';rerender();};const remove=el('button','ลบ scheme','danger');remove.onclick=()=>{if(p.terms.some(t=>t.scheme===scheme.id))return message('ย้ายแนวคิดออกจาก scheme นี้ก่อนลบ เพื่อรักษาคำและการอ้างอิง');mutate(()=>{p.schemes=p.schemes.filter(s=>s.id!==scheme.id);state.editScheme='';});};editor.append(close,remove);detail.append(editor);layout.append(aside,detail);hierarchy.append(layout);root.append(hierarchy,checkCard());return;}}const term=p.terms.find(t=>t.id===state.selected)||first;if(term){state.selected=term.id;detail.append(el('h3',term.labelEn+' · '+(term.labelTh||'')),el('p','skos:Concept · '+(p.schemes.find(s=>s.id===term.scheme)?.label||'ยังไม่อยู่ใน scheme'),'muted'));
const makeSelect=(label,value,options,callback)=>{const l=el('label',label),s=el('select');s.setAttribute('aria-label',label);for(const [id,text]of options){const o=el('option',text);o.value=id;s.append(o);}s.value=value;s.onchange=()=>callback(s.value);l.append(s);return l;};
const parents=p.hierarchy.filter(e=>e.child===term.id);const parentGrid=el('div',undefined,'grid');const parentOptions=[['','— top concept —'],...p.terms.filter(t=>t.id!==term.id&&parentAllowed(p,term.id,t.id)).map(t=>[t.id,t.labelEn+' · '+(t.labelTh||'')])];parentGrid.append(makeSelect('Broader concept · skos:broader',parents[0]?.parent||'',parentOptions,value=>mutate(()=>{if(parents[0]){if(value)parents[0].parent=value;else p.hierarchy=p.hierarchy.filter(e=>e.id!==parents[0].id);}else if(value)p.hierarchy.push({id:'broader-'+crypto.randomUUID(),child:term.id,parent:value,scheme:term.scheme,rationale:'',status:'proposed'});})),makeSelect('Scheme',term.scheme||'',[['','— ยังไม่จัด scheme —'],...p.schemes.map(s=>[s.id,s.label])],value=>mutate(()=>{term.scheme=value;for(const e of parents)e.scheme=value;})));detail.append(parentGrid);
const extraParent=makeSelect('เพิ่ม broader อีกแนวคิด','',[['','— เลือก broader concept เพิ่ม —'],...parentOptions.filter(([id])=>id&&!parents.some(e=>e.parent===id))],value=>{if(value)mutate(()=>p.hierarchy.push({id:'broader-'+crypto.randomUUID(),child:term.id,parent:value,scheme:term.scheme,rationale:'',status:'proposed'}));});const advancedParents=el('details');advancedParents.append(el('summary','Polyhierarchy · เพิ่ม broader concept'),extraParent);detail.append(advancedParents);if(parents.length)for(const edge of parents){detail.append(el('p','Is-a test: '+nameOf(p,term.id)+' is a type of '+nameOf(p,edge.parent)),el('p','สถานะ: '+(edge.status||'proposed')+' · ต้องทบทวนความหมายโดยเจ้าของ','muted'),control('rationale','Is-a rationale*',edge.rationale,v=>edge.rationale=v),control('status',['proposed','reviewed'],edge.status||'proposed',v=>edge.status=v));if(parents.length>1){const remove=el('button','ลบ broader · '+nameOf(p,edge.parent));remove.onclick=()=>mutate(()=>p.hierarchy=p.hierarchy.filter(e=>e.id!==edge.id));detail.append(remove);}}else detail.append(el('p','Top concept · ไม่มี broader concept','muted'));
detail.append(el('p','ความสัมพันธ์ part-of และลำดับการทำงานจัดใน Thesaurus / Ontology ไม่ใช้แทน is-a','muted'),control('definitionEn','Definition · จาก Controlled vocabulary (English)*',term.definitionEn,v=>term.definitionEn=v),control('definitionTh','Definition · ภาษาไทย*',term.definitionTh,v=>term.definitionTh=v));const depth=treeRows(p,term.scheme).find(r=>r.term.id===term.id)?.depth||1;detail.append(el('p','Depth '+depth+' · Alternative labels: '+[term.aliasesEn,term.aliasesTh].filter(Boolean).join(' / '),'muted'));
const scheme=p.schemes.find(s=>s.id===term.scheme);if(scheme){const settings=el('details');settings.append(el('summary','แก้ไขชื่อและขอบเขต scheme'),control('label','Scheme label',scheme.label,v=>{scheme.label=v;}),control('scope','Scheme scope*',scheme.scope,v=>scheme.scope=v));const refresh=el('button','แสดงชื่อ scheme ที่แก้แล้ว');refresh.onclick=rerender;settings.append(refresh);detail.append(settings);}
const remove=el('button','Remove from the scheme','danger');remove.onclick=()=>mutate(()=>{term.scheme='';p.hierarchy=p.hierarchy.filter(e=>e.child!==term.id);message('นำออกจาก scheme และถอด broader ของแนวคิดนี้แล้ว คำใน CV ยังคงอยู่ · ย้อนกลับได้');});detail.append(remove);}else detail.append(el('p','เพิ่มคำใน Controlled vocabulary แล้วเลือก scheme เพื่อเริ่มจัดลำดับ'));
layout.append(aside,detail);hierarchy.append(layout);root.append(hierarchy,checkCard());const footer=el('div',undefined,'actions');const nextButton=el('button','Continue to thesaurus →','primary');nextButton.onclick=next;footer.append(nextButton);root.append(footer);
}
