const BOOKS_DATA = [
  {"isbn": "9781250374745", "title": "On Photography", "subtitle": null, "authors": ["Susan Sontag"], "publisher": "Picador", "year": 2025, "pages": 224, "format": "paperback", "lang": "English", "cats": ["philosophy", "Photography"], "rank": 1, "cover": "covers/9781250374745.jpg", "subjects": ["philosophy", "Photography"], "media": "Book"},
  {"isbn": "9783836571890", "title": "Annie Leibovitz. The Early Years, 1970-1983", "subtitle": null, "authors": ["Lucy Sante", "Jann Wenner"], "publisher": "TASCHEN", "year": 2018, "pages": 180, "format": "hardcover (ปกแข็ง)", "lang": "English", "cats": ["Photography", "celebrities", "exhibitions", "portraits"], "rank": 1, "cover": "covers/9783836571890.jpg", "subjects": ["Photography", "celebrities", "exhibitions", "portraits"], "media": "Book"},
  {"isbn": "9780393244793", "title": "The Book", "subtitle": null, "authors": ["Keith Houston"], "publisher": "W. W. Norton & Company, W.W. Norton & Company", "year": 2016, "pages": 428, "format": "hardcover (ปกแข็ง)", "lang": "English", "cats": ["book  history", "history", "paper"], "rank": 1, "cover": "covers/9780393244793.jpg", "subjects": ["book  history", "history", "paper"], "media": "Book"},
  {"isbn": "9780241197264", "title": "The Startup Way", "subtitle": null, "authors": ["eric ries"], "publisher": "Portfolio Penguin", "year": 2017, "pages": null, "format": "paperback (ปกอ่อน)", "lang": "English", "cats": ["startup", "entrepreneurship"], "rank": 1, "cover": "covers/9780241197264.jpg", "subjects": ["startup", "entrepreneurship"], "media": "Book"},
  {"isbn": "9789740217176", "title": "มนุษย์อยุธยา ประวัติศาสตร์สังคม จากข้าวปลา หยูกยา ตำรา Sex", "subtitle": null, "authors": ["กำพล จำปาพันธ์"], "publisher": "มติชน", "year": null, "pages": 338, "format": "paperback (ปกอ่อน)", "lang": "ไทย", "cats": ["หนังสือสารคดี"], "rank": 1, "cover": "covers/9789740217176.jpg", "subjects": ["หนังสือสารคดี"], "media": "Book"},
  {"isbn": "9780241977736", "title": "Gastrophysics", "subtitle": null, "authors": ["Charles Spence"], "publisher": "Viking, Penguin Books, Limited", "year": 2017, "pages": null, "format": "paperback (ปกอ่อน)", "lang": "English", "cats": ["gastrophysics", "food habits"], "rank": 1, "cover": "covers/9780241977736.jpg", "subjects": ["gastrophysics", "food habits"], "media": "Book"},
  {"isbn": "9780738773568", "title": "The Enchanted Heart", "subtitle": null, "authors": ["Alana Fairchild", "Lindy Longhurst"], "publisher": "Llewellyn Publications", "year": 2022, "pages": 8, "format": null, "lang": "English", "cats": ["Books"], "rank": 1, "cover": "covers/9780738773568.jpg", "subjects": [], "media": "Book"},
  {"isbn": "9781401940256", "title": "Psychic Tarot for the Heart Oracle Deck", "subtitle": null, "authors": ["Holland", "John"], "publisher": "Hay House, Incorporated", "year": 2014, "pages": null, "format": null, "lang": "English", "cats": ["psychic ability", "tarot"], "rank": 1, "cover": "covers/9781401940256.jpg", "subjects": ["psychic ability", "tarot"], "media": "Book"},
  {"isbn": "9781401964313", "title": "Absolute Affirmations", "subtitle": null, "authors": ["Krystal Banner"], "publisher": "Kaleidadope, LLC, Hay House, Incorporated", "year": 2018, "pages": null, "format": null, "lang": "English", "cats": ["Books"], "rank": 2, "cover": "covers/9781401964313.jpg", "subjects": [], "media": "Book"},
  {"isbn": "9781572819887", "title": "Pixiekins", "subtitle": null, "authors": ["Paulina Cassidy"], "publisher": "U.S. Games Systems, Incorporated", "year": 2019, "pages": null, "format": null, "lang": "English", "cats": ["Books"], "rank": 3, "cover": "covers/9781572819887.jpg", "subjects": [], "media": "Book"},
  {"isbn": "9781925682823", "title": "Magick of You Oracle", "subtitle": null, "authors": ["Fiona Horne"], "publisher": "Rockpool Publishing", "year": 2019, "pages": null, "format": null, "lang": "English", "cats": ["Books"], "rank": 4, "cover": "covers/9781925682823.jpg", "subjects": [], "media": "Book"},
  {"isbn": "9781577313113", "title": "The Power of Now", "subtitle": null, "authors": ["Eckhart Tolle"], "publisher": "Norma Ediciones S a, Namaste Publishing", "year": 1997, "pages": null, "format": null, "lang": "English", "cats": ["meditación", "nonfiction", "religion"], "rank": 1, "cover": "covers/9781577313113.jpg", "subjects": ["meditación", "nonfiction", "religion"], "media": "Book"},
  {"isbn": "9781401951580", "title": "Sacred Traveler Oracle Cards", "subtitle": null, "authors": ["Denise Linn"], "publisher": "Lifestyles", "year": 2017, "pages": null, "format": null, "lang": "English", "cats": ["psychology"], "rank": 1, "cover": "covers/9781401951580.jpg", "subjects": ["psychology"], "media": "Book"},
  {"isbn": "9781922579027", "title": "Finding Inner Peace Inspiration Cards", "subtitle": null, "authors": ["Olivia Burki"], "publisher": "Rockpool Publishing", "year": 2022, "pages": null, "format": null, "lang": "English", "cats": ["Books"], "rank": 5, "cover": "covers/9781922579027.jpg", "subjects": [], "media": "Book"},
  {"isbn": "9781401944711", "title": "The Soul's Journey Lesson Cards", "subtitle": null, "authors": ["James Van Praagh"], "publisher": "Lifestyles", "year": 2014, "pages": null, "format": null, "lang": "English", "cats": ["self-actualization (psychology)", "conduct of life", "spirituality"], "rank": 1, "cover": "covers/9781401944711.jpg", "subjects": ["self-actualization (psychology)", "conduct of life", "spirituality"], "media": "Book"},
  {"isbn": "9781401962036", "title": "The Dream Weaver's Oracle", "subtitle": null, "authors": ["Colette Baron-Reid", "Joel Nakamura"], "publisher": "Hay House Inc.", "year": 2023, "pages": null, "format": null, "lang": "English", "cats": ["Books"], "rank": 6, "cover": "covers/9781401962036.jpg", "subjects": [], "media": "Book"}
];
const EXPORT_META = {"date": "2026-07-24", "items": 16};
