const BOOKS_DATA = [
  {"isbn": "9781250374745", "title": "On Photography", "subtitle": null, "authors": ["Susan Sontag"], "publisher": "Picador", "year": 2025, "pages": 224, "format": "paperback", "lang": "English", "cats": ["philosophy", "Photography"], "rank": 1, "cover": "covers/9781250374745.jpg", "subjects": ["philosophy", "Photography"], "media": "Book"},
  {"isbn": "9783836571890", "title": "Annie Leibovitz. The Early Years, 1970-1983", "subtitle": null, "authors": ["Lucy Sante", "Jann Wenner"], "publisher": "TASCHEN", "year": 2018, "pages": 180, "format": "hardcover (ปกแข็ง)", "lang": "English", "cats": ["Photography", "celebrities", "exhibitions", "portraits"], "rank": 1, "cover": "covers/9783836571890.jpg", "subjects": ["Photography", "celebrities", "exhibitions", "portraits"], "media": "Book"},
  {"isbn": "9780393244793", "title": "The Book", "subtitle": null, "authors": ["Keith Houston"], "publisher": "W. W. Norton & Company, W.W. Norton & Company", "year": 2016, "pages": 428, "format": "hardcover (ปกแข็ง)", "lang": "English", "cats": ["book", "paper", "history", "book  history"], "rank": 1, "cover": "covers/9780393244793.jpg", "subjects": ["book", "paper", "history", "book  history"], "media": "Book"},
  {"isbn": "9780241197264", "title": "The Startup Way", "subtitle": null, "authors": ["eric ries"], "publisher": "Portfolio Penguin", "year": 2017, "pages": null, "format": "paperback (ปกอ่อน)", "lang": "English", "cats": ["startup", "entrepreneurship"], "rank": 1, "cover": "covers/9780241197264.jpg", "subjects": ["startup", "entrepreneurship"], "media": "Book"},
  {"isbn": "9789740217176", "title": "มนุษย์อยุธยา ประวัติศาสตร์สังคม จากข้าวปลา หยูกยา ตำรา Sex", "subtitle": null, "authors": ["กำพล จำปาพันธ์"], "publisher": "มติชน", "year": null, "pages": 338, "format": "paperback (ปกอ่อน)", "lang": "ไทย", "cats": ["หนังสือสารคดี"], "rank": 1, "cover": "covers/9789740217176.jpg", "subjects": ["หนังสือสารคดี"], "media": "Book"},
  {"isbn": "9780241977736", "title": "Gastrophysics", "subtitle": null, "authors": ["Charles Spence"], "publisher": "Viking, Penguin Books, Limited", "year": 2017, "pages": null, "format": "paperback (ปกอ่อน)", "lang": "English", "cats": ["gastrophysics", "food habits"], "rank": 1, "cover": "covers/9780241977736.jpg", "subjects": ["gastrophysics", "food habits"], "media": "Book"},
  {"isbn": "9787500676911", "title": "Wikinomics", "subtitle": null, "authors": ["Don Tapscott", "Anthony D. Williams"], "publisher": "Portfolio, Penguin Group USA, Inc.", "year": 2006, "pages": null, "format": null, "lang": "English", "cats": ["Business", "web 2.0", "wiki"], "rank": 1, "cover": "covers/9787500676911.jpg", "subjects": ["Business", "web 2.0", "wiki"], "media": "Book"},
  {"isbn": null, "title": "THE LIFE OF THE COSMOS", "subtitle": null, "authors": ["Lee Smolin"], "publisher": null, "year": null, "pages": null, "format": "paperback", "lang": "English", "cats": ["cosmology", "physics", "science"], "rank": 1, "cover": null, "subjects": ["cosmology", "physics", "science"], "media": "Book"},
  {"isbn": "9780393339857", "title": "\"Surely You're Joking, Mr. Feynman\"", "subtitle": null, "authors": ["Richard Phillips Feynman", "Ralph Leighton"], "publisher": "W. W. Norton & Company, Unwin Paperbacks", "year": 1984, "pages": null, "format": null, "lang": "English", "cats": ["music", "humor", "art"], "rank": 1, "cover": "covers/9780393339857.jpg", "subjects": ["music", "humor", "art"], "media": "Book"},
  {"isbn": "9780755314089", "title": "I, Woz", "subtitle": null, "authors": ["Steve Wozniak"], "publisher": "Headline Publishing Group", "year": 2007, "pages": null, "format": null, "lang": "English", "cats": ["biography", "engineers", "inc.", "apple computer"], "rank": 1, "cover": "covers/9780755314089.jpg", "subjects": ["biography", "engineers", "inc.", "apple computer"], "media": "Book"},
  {"isbn": "9781408703748", "title": "Steve Jobs", "subtitle": null, "authors": [], "publisher": "Little, Brown", "year": 2011, "pages": null, "format": "hardcover (ปกแข็ง)", "lang": "English", "cats": ["Business", "general", "history", "apple", "biology", "creative"], "rank": 2, "cover": "covers/9781408703748.jpg", "subjects": ["Business", "general", "history", "apple", "biology", "creative"], "media": "Book"},
  {"isbn": "9781452166780", "title": "The coffee dictionary", "subtitle": null, "authors": ["Maxwell Colonna-Dashwood"], "publisher": "Chronicle Books LLC, Octopus Publishing Group", "year": 2017, "pages": null, "format": "hardcover (ปกแข็ง)", "lang": "English", "cats": ["Coffee", "dictionaries", "cooking (coffee)"], "rank": 1, "cover": "covers/9781452166780.jpg", "subjects": ["Coffee", "dictionaries", "cooking (coffee)"], "media": "Book"},
  {"isbn": "9780241972717", "title": "The Startup Way", "subtitle": null, "authors": ["Eric Ries"], "publisher": "Knopf Doubleday Publishing Group, Penguin Books, Limited", "year": 2017, "pages": null, "format": "paperback (ปกอ่อน)", "lang": "English", "cats": ["corporate culture", "entrepreneurship"], "rank": 1, "cover": "covers/9780241972717.jpg", "subjects": ["corporate culture", "entrepreneurship"], "media": "Book"},
  {"isbn": "9781118960875", "title": "The lean product playbook", "subtitle": null, "authors": ["Dan Olsen"], "publisher": "Wiley", "year": 2015, "pages": null, "format": "hardcover (ปกแข็ง)", "lang": "English", "cats": ["consumer satisfaction", "lean manufacturing", "manufacturers"], "rank": 1, "cover": "covers/9781118960875.jpg", "subjects": ["consumer satisfaction", "lean manufacturing", "manufacturers"], "media": "Book"},
  {"isbn": null, "title": "The Shakespeare and Company Book of Interviews", "subtitle": null, "authors": ["Adam Biles"], "publisher": null, "year": null, "pages": null, "format": "hardcover (ปกแข็ง)", "lang": "English", "cats": ["book", "bookshop"], "rank": 2, "cover": null, "subjects": ["book", "bookshop"], "media": "Book"}
];
const EXPORT_META = {"date": "2026-07-27", "items": 15};
