import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import {validate,files,clone,zip} from '../src/studio/model.mjs';
const seed=JSON.parse(fs.readFileSync(new URL('../src/studio/seed.json',import.meta.url)));
test('Seed is structural public data: 35 terms, 41 fields, 14 hand planes; no inventory',()=>{assert.deepEqual(validate(seed),[]);assert.equal(seed.terms.length,35);assert.equal(seed.fields.length,41);assert.equal(seed.fields.filter(x=>x.id.startsWith('hand_plane.')).length,14);assert.equal(seed.individuals.length,0);assert.equal(seed.triples.length,0);assert.doesNotMatch(JSON.stringify(seed),/AST-\d{6}|sourceUUID|sourceHash|originalValue/);});
test('Dangling references and hierarchy cycles block semantic export',()=>{let p=clone(seed);p.terms=p.terms.filter(x=>x.id!=='asset-concept-hand-plane');assert(validate(p).some(x=>x.includes('Hierarchy')));assert.throws(()=>files(p));p=clone(seed);p.hierarchy.push({id:'cycle',child:'asset-concept-woodworking-tool',parent:'asset-concept-hand-plane'});assert(validate(p).some(x=>x.includes('วงจร')));});
test('Literal escaping and JSON-LD roundtrip keep source text and leading zeros',()=>{let p=clone(seed);p.triples.push({id:'literal',subject:'urn:test:s',predicate:'urn:test:p',object:'00123 "quoted"\nไทย <script>',kind:'literal'});const f=files(p),nodes=JSON.parse(f['knowledge-graph.jsonld'])['@graph'];assert.equal(nodes.find(n=>n['@id']==='urn:test:s')['urn:test:p'][0]['@value'],p.triples[0].object);assert.match(f['knowledge-graph.ttl'],/00123 \\"quoted\\"/);});
test('SHACL cardinality emitted as integer and ZIP includes all exports',async()=>{let f=files(seed);assert.match(f['shapes.ttl'],/minCount> 1 \./);const b=new Uint8Array(await zip(f).arrayBuffer());assert.equal(new DataView(b.buffer).getUint32(0,true),0x04034b50);assert.equal(new DataView(b.buffer).getUint16(b.length-12,true),Object.keys(f).length);});
test('Invalid IRI is rejected without accepting injected Turtle',()=>{let p=clone(seed);p.terms[0].uri='urn:x> . <urn:hack';assert(validate(p).length>0);assert.throws(()=>files(p));});

test("Ontology record and class definitions survive RDF export; private drafts excluded from website projection",()=>{let p=clone(seed);p.config.title="Owner ontology";p.classes[0].definition="An example class definition";p.content.push({id:"private",title:"Private evidence",source:"secret",status:"ready",access:"private"},{id:"public",title:"Reader title",source:"private locator",status:"ready",access:"public"});const f=files(p);assert.match(f["ontology.ttl"],/Owner ontology/);assert.match(f["ontology.ttl"],/An example class definition/);assert.doesNotMatch(f["website\/content.json"],/secret|private locator|Private evidence/);assert.match(f["website\/content.json"],/Reader title/);});
