import {domains,domainOf,domainRecords,domainIdeas} from './domains.js';
import {emptyDB,id,kinds,profiles,bases,events,validateDB,exportGraph,removeRecord} from './model.js';
const $=s=>document.querySelector(s), el=(tag,text,cls)=>{const e=document.createElement(tag);if(text!==undefined)e.textContent=text;if(cls)e.className=cls;return e;};
const activeDomain=document.body.dataset.domain||null,app=domains[activeDomain];
const scopedRecords=()=>domainRecords(db,activeDomain),scopedIdeas=()=>domainIdeas(db,activeDomain);
const KEY='noppadol.asset-studio.v1';let db=emptyDB(),catalog,vocabulary,thesaurus,taxonomy,fields=[],selectedConcepts=new Set(),editingObservations=[],storageBlocked=false,staleDraft=false,loadedSnapshot=null,currentProfile="hand_plane";
const status=(text,error=false)=>{const e=$('#status');e.textContent=text;e.classList.toggle('error',error);};
function options(select,entries,blank){select.replaceChildren();if(blank)select.add(new Option(blank,''));for(const [value,label] of entries)select.add(new Option(label,value));}
const item=r=>['AssetItem','Component'].includes(r.kind);
const fieldByID=k=>fields.find(f=>f.key===k);
function commit(next){if(staleDraft)throw new Error('อีกแท็บมีการเปลี่ยนข้อมูล กรุณาคัดลอกสิ่งที่พิมพ์ไว้แล้วปิดและเปิดฟอร์มใหม่ก่อนบันทึก');const errors=validateDB(next,catalog,vocabulary);if(errors.length)throw new Error(errors.join('\n'));if(storageBlocked)throw new Error('ข้อมูลเดิมในเครื่องอ่านไม่ได้ กรุณานำเข้าไฟล์สำรองที่ถูกต้องก่อนบันทึก');try{if(localStorage.getItem(KEY)!==loadedSnapshot)throw new Error('conflict');const serialized=JSON.stringify(next);localStorage.setItem(KEY,serialized);loadedSnapshot=serialized;}catch(error){if(error.message==='conflict')throw new Error('มีข้อมูลใหม่จากอีกแท็บ กรุณาคัดลอกสิ่งที่พิมพ์แล้วโหลดหน้าใหม่');throw new Error('บันทึกไม่สำเร็จ พื้นที่เก็บข้อมูลอาจเต็มหรือถูกปิดกั้น ข้อมูลเดิมยังอยู่ กรุณาสำรองข้อมูลก่อน');}db=next;render();$('#save-state').textContent='บันทึกในเครื่องแล้ว · '+new Date().toLocaleTimeString('th-TH');}
function card(r,idea=false){const e=el('article',undefined,'card');e.append(el('span',idea?'CREATIVE PROPOSAL':kinds[r.kind],'badge'),el('h3',r.title));e.append(el('p',idea?r.mission:profiles[r.profile]+' · '+r.observations.length+' รายละเอียด'),el('p','ฉบับร่าง · ยังไม่ผ่านการทบทวน'));const actions=el('div',undefined,'actions');const edit=el('button','เปิด / แก้ไข');edit.onclick=()=>idea?openIdea(r):openRecord(r);const del=el('button','ลบ');del.onclick=()=>{if(!confirm('ลบ “'+r.title+'” ออกจากเครื่องนี้?'))return;try{commit(removeRecord(db,r.id));status('ลบรายการแล้ว');}catch(e){status(e.message,true);}};actions.append(edit,del);e.append(actions);return e;}
function render(){
 $('#record-count').textContent=scopedRecords().length;$('#idea-count').textContent=scopedIdeas().length;
 const q=$('#search').value.normalize('NFC').toLocaleLowerCase();const rows=scopedRecords().filter(r=>r.title.toLocaleLowerCase().includes(q)||r.concepts.some(uri=>conceptText(vocabulary.concepts.find(c=>c.uri===uri)).includes(q)));
 $('#records').replaceChildren(...rows.map(r=>card(r)));if(!rows.length){const e=el('div',undefined,'empty');e.append(el('div','◇','symbol'),el('h3',scopedRecords().length?'ยังไม่พบรายการที่ค้นหา':app?.empty||'เริ่มต้นด้วยสิ่งของหนึ่งชิ้น'),el('p',app?.hint||'เลือกแอปงานไม้ แผ่นเสียง หรือกล้อง เพื่อเริ่มด้วยแบบกรอกที่ตรงกับสิ่งของของคุณ'));$('#records').append(e);}
 $('#idea-list').replaceChildren(...scopedIdeas().map(r=>card(r,true)));if(!scopedIdeas().length){const e=el('div',undefined,'empty');e.append(el('h3','เรื่องราวใหม่ อาจเริ่มจากสิ่งที่มีอยู่'),el('p','เพิ่มทรัพย์สินก่อน แล้วเชื่อมสิ่งของกับ Mission และไอเดียที่อยากพัฒนา'));$('#idea-list').append(e);}
 if(!$('#graph').hidden)drawGraph();
}
function conceptText(c){return c?JSON.stringify([c.prefLabel,c.altLabel,c.hiddenLabel]).normalize('NFC').toLocaleLowerCase():'';}
function renderConcepts(){const q=$('#concept-search').value.normalize('NFC').toLocaleLowerCase();$('#concepts').replaceChildren();const source=thesaurus.concepts||vocabulary.concepts;for(const c of source){const category=taxonomy.collections.find(x=>x.id===$('#concept-category').value);if(!selectedConcepts.has(c.uri)&&(!conceptText(c).includes(q)||(category&&!category.members.includes(c.id))))continue;const label=el('label',undefined,'concept-option');const check=el('input');check.type='checkbox';check.value=c.uri;check.checked=selectedConcepts.has(c.uri);check.onchange=()=>check.checked?selectedConcepts.add(c.uri):selectedConcepts.delete(c.uri);const span=el('span',c.prefLabel.th||c.prefLabel.en);const original=vocabulary.concepts.find(x=>x.uri===c.uri);span.append(el('small',original?.definition||''));const parent=taxonomy.hierarchy.filter(h=>h.narrower===c.id).map(h=>vocabulary.concepts.find(x=>x.id===h.broader)?.prefLabel.th).filter(Boolean);const related=thesaurus.related.filter(h=>h.a===c.id||h.b===c.id).map(h=>vocabulary.concepts.find(x=>x.id===(h.a===c.id?h.b:h.a))?.prefLabel.th).filter(Boolean);if(parent.length)span.append(el('small','หมวดกว้าง: '+parent.join(', ')));if(related.length)span.append(el('small','เกี่ยวข้อง: '+related.join(', ')));label.append(check,span);$('#concepts').append(label);}}
function relations(r={}){r=r||{};const box=$('#relationships');box.replaceChildren();const kind=$('#kind').value;const keys=item({kind})?[['model','ProductModel','รุ่นที่อ้างอิง'],['edition','ReleaseEdition','ฉบับที่อ้างอิง']]:kind==='ReleaseEdition'?[['releaseGroup','ReleaseGroup','กลุ่มฉบับ']]:kind==='TrackEntry'?[['inEdition','ReleaseEdition','ฉบับของแทร็ก *']]:[];for(const [key,target,labelText] of keys){if(app&&((key==='edition'&&activeDomain!=='records')||(key==='model'&&activeDomain==='records'))&&!r[key])continue;const label=el('label',labelText);const select=el('select');select.dataset.relation=key;options(select,db.records.filter(x=>x.kind===target&&x.id!==r.id).map(x=>[x.id,x.title]),'ยังไม่ระบุ');select.value=r[key]||'';select.required=key==='inEdition';label.append(select);box.append(label);}if(kind==='Component'){const label=el('label','เป็นส่วนประกอบของ'),s=el('select');s.dataset.relation='parent';options(s,db.records.filter(x=>item(x)&&x.id!==r.id).map(x=>[x.id,x.title]),'ยังไม่ระบุ');s.value=r.parent||'';label.append(s);box.append(label);}
if(kind==='AssetEvent'){for(const [key,title,entries] of [['eventKind','กิจกรรม',Object.entries(events)],['participant','ทรัพย์สินที่ใช้',db.records.filter(item).map(x=>[x.id,x.title])]]){const l=el('label',title),s=el('select');s.dataset.relation=key;s.required=true;options(s,entries,'เลือกรายการ');s.value=r[key]||'';l.append(s);box.append(l);}const l=el('label','วันที่กิจกรรม (ถ้าทราบ)'),i=el('input');i.type='date';i.dataset.relation='eventDate';i.value=r.eventDate||'';l.append(i);box.append(l);}
$('#concept-fieldset').hidden=!item({kind});}
function picker(){const p=$('#profile').value;options($('#field-picker'),fields.filter(f=>(f.group==='common'||f.group===p)&&!editingObservations.some(o=>o.field===f.key)).map(f=>[f.key,f.label_th+(f.priority==='recommended'?' · แนะนำ':'')]));}
const scopes={model:'รุ่นผลิตภัณฑ์',item:'รายชิ้น',model_or_item:'รุ่นหรือรายชิ้น',item_or_batch:'รายชิ้นหรือชุดผลิต',acquisition:'การได้มา',dated_observation:'ข้อสังเกตตามเวลา',release:'ฉบับเผยแพร่',edition:'ฉบับเผยแพร่',copy:'สำเนาที่ถือครอง',track:'แทร็ก'};
function observations(){const box=$('#observations');box.replaceChildren();editingObservations.forEach((o,index)=>{
 const f=fieldByID(o.field);const wrap=el('div',undefined,'observation');const head=el('div',undefined,'observation-head');const remove=el('button','นำออก');remove.type='button';remove.onclick=()=>{editingObservations.splice(index,1);observations();picker();};head.append(el('b',f.label_th),remove);wrap.append(head,el('p','ระดับข้อมูล: '+(scopes[f.appliesTo]||f.appliesTo)+' · '+f.valueType,'hint'));
 const grid=el('div',undefined,'form-grid');const select=(title,entries,value,change)=>{const label=el('label',title),input=el('select');options(input,Object.entries(entries));input.value=value;input.onchange=()=>change(input.value);label.append(input);grid.append(label);return input;};
 select('สถานะ',{known:'มีค่าที่บันทึก',unknown:'ยังไม่ทราบ',not_applicable:'ไม่เกี่ยวข้อง'},o.status,v=>{o.status=v;if(v!=='known'){o.value='';o.unit='';}observations();});
 if(o.status==='known'){
 select('วิธีได้ข้อมูล',bases,o.basis,v=>o.basis=v);
 select('รูปแบบค่า',{text:'ข้อความ / JSON ต้นทาง',number:'ตัวเลข + หน่วย',reference:'อ้างอิงรายการในทะเบียน'},o.type,v=>{o.type=v;o.value='';o.unit='';observations();});
 const label=el('label',o.type==='reference'?'รายการที่อ้างอิง':'ค่า');let input;
 if(o.type==='reference'){input=el('select');options(input,db.records.map(r=>[r.id,r.title]),'เลือกรายการ');}
 else {input=el('input');input.type='text';input.maxLength=10000;if(o.type==='number')input.inputMode='decimal';}
 input.value=o.value;input.required=true;input.oninput=()=>o.value=input.value;label.append(input);grid.append(label);
 if(o.type==='number'){const l=el('label','หน่วย *'),i=el('input');i.required=true;i.placeholder='เช่น mm, deg, THB';i.value=o.unit;i.oninput=()=>o.unit=i.value;l.append(i);grid.append(l);}
 }wrap.append(grid);box.append(wrap);
});}
function openRecord(r,preset){staleDraft=false;$('#entry-form').reset();$('#form-error').textContent='';$('#record-id').value=r?.id||'';$('#editor-title').textContent=r?'แก้ไขรายการ':'เพิ่มรายการ';$('#title').value=r?.title||'';$('#creator').value=r?.creator||db.records.at(-1)?.creator||'';options($('#kind'),Object.entries(kinds).filter(([k])=>!app||app.kinds.includes(k)||k===r?.kind));options($('#profile'),Object.entries(profiles).filter(([k])=>!app||app.profiles.includes(k)||k===r?.profile));$('#kind').value=r?.kind||preset?.kind||'AssetItem';$('#profile').value=r?.profile||preset?.profile||app?.profiles[0]||'hand_plane';$('#record-domain').value=r?domainOf(r)||'':activeDomain||'';currentProfile=$('#profile').value;$('#source-text').value=r?.sourceText||'';$('#source-url').value=r?.sourceURL||'';selectedConcepts=new Set(r?.concepts||(preset?.concept?['urn:noppadol:assets:concept:'+preset.concept]:[]));editingObservations=structuredClone(r?.observations||(preset?.fields||[]).map(field=>({field,status:'unknown',basis:'owner_reported',type:'text',value:'',unit:''})));$('#concept-category').value=app?.category||'';relations(r);if(!r&&preset?.kind==='AssetEvent'){$('[data-relation=eventKind]').value=activeDomain==='records'?'listening':'use';}picker();observations();renderConcepts();$('#editor').showModal();$('#title').focus();}
function openIdea(r){staleDraft=false;$('#idea-form').reset();$('#idea-error').textContent='';$('#idea-id').value=r?.id||'';for(const [selector,key] of [['idea-title','title'],['mission','mission'],['idea-creator','creator'],['rationale','rationale'],['limits','limits'],['idea-source','sourceText']])$('#'+selector).value=r?.[key]||'';$('#idea-assets').replaceChildren();for(const asset of db.records.filter(item)){const l=el('label',undefined,'concept-option'),i=el('input');i.type='checkbox';i.value=asset.id;i.checked=r?.assets.includes(asset.id)||false;l.append(i,el('span',asset.title+' · '+(domains[domainOf(asset)]?.name||'คลังกลาง')));$('#idea-assets').append(l);}if(!db.records.some(item))$('#idea-assets').append(el('p','เพิ่มทรัพย์สินรายชิ้นก่อนบันทึกไอเดีย'));$('#idea-editor').showModal();}
$('#entry-form').onsubmit=e=>{e.preventDefault();try{
 const old=db.records.find(r=>r.id===$('#record-id').value),now=new Date().toISOString();const r={id:old?.id||id(),createdAt:old?.createdAt||now,updatedAt:now,title:$('#title').value.trim(),creator:$('#creator').value.trim(),domain:$('#record-domain').value||undefined,kind:$('#kind').value,profile:$('#profile').value,concepts:item({kind:$('#kind').value})?[...selectedConcepts]:[],sourceText:$('#source-text').value.trim(),sourceURL:$('#source-url').value.trim(),observations:structuredClone(editingObservations)};
 for(const s of document.querySelectorAll('[data-relation]'))r[s.dataset.relation]=s.value;
 commit({...db,records:old?db.records.map(x=>x.id===r.id?r:x):[...db.records,r]});$('#editor').close();status('บันทึกแล้ว — ข้อมูลยังเป็นฉบับร่างส่วนตัว');
 }catch(err){$('#form-error').textContent=err.message;}};
$('#idea-form').onsubmit=e=>{e.preventDefault();try{const old=db.ideas.find(r=>r.id===$('#idea-id').value),now=new Date().toISOString();const r={id:old?.id||id(),createdAt:old?.createdAt||now,updatedAt:now,assets:[...document.querySelectorAll('#idea-assets input:checked')].map(x=>x.value)};for(const [selector,key] of [['idea-title','title'],['mission','mission'],['idea-creator','creator'],['rationale','rationale'],['limits','limits'],['idea-source','sourceText']])r[key]=$('#'+selector).value.trim();commit({...db,ideas:old?db.ideas.map(x=>x.id===r.id?r:x):[...db.ideas,r]});$('#idea-editor').close();status('บันทึกไอเดียแล้ว — ความเชื่อมโยงนี้เป็นข้อเสนอสร้างสรรค์');}catch(err){$('#idea-error').textContent=err.message;}};
$('#kind').onchange=()=>relations();$('#profile').onchange=()=>{if(editingObservations.some(o=>!o.field.startsWith('common.'))&&!confirm('เปลี่ยนแบบข้อมูลจะนำรายละเอียดเฉพาะแบบเดิมออกจากฟอร์ม ต้องการเปลี่ยนหรือไม่?')){$('#profile').value=currentProfile;return;}currentProfile=$('#profile').value;editingObservations=editingObservations.filter(o=>o.field.startsWith('common.'));picker();observations();};$('#concept-search').oninput=renderConcepts;$('#concept-category').onchange=renderConcepts;
$('#add-field').onclick=()=>{const key=$('#field-picker').value;if(!key)return;editingObservations.push({field:key,status:'known',basis:'owner_reported',type:'text',value:'',unit:''});picker();observations();};
$('#new-record').onclick=()=>openRecord();$('#new-idea').onclick=()=>openIdea();$('#search').oninput=render;
for(const button of document.querySelectorAll('[data-close]'))button.onclick=()=>$('#'+button.dataset.close).close();
for(const button of document.querySelectorAll('[data-tab]'))button.onclick=()=>{for(const panel of document.querySelectorAll('.panel'))panel.hidden=panel.id!==button.dataset.tab;for(const b of document.querySelectorAll('[data-tab]'))b.setAttribute('aria-pressed',String(b===button));if(button.dataset.tab==='graph')drawGraph();};
function download(name,data,type='application/json'){const url=URL.createObjectURL(new Blob([data],{type}));const a=el('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
$('#backup').onclick=()=>download('noppadol-assets-backup-'+new Date().toISOString().slice(0,10)+'.json',JSON.stringify(db,null,2));
$('#export').onclick=async()=>{try{download('noppadol-assets-graph.jsonld',JSON.stringify(await exportGraph(db,catalog,vocabulary),null,2),'application/ld+json');status('ส่งออกกราฟรวมทุกแอปฉบับร่างแล้ว ใช้ข้อกำหนดใน standards ตรวจ SHACL ก่อนนำเข้าระบบจริง');}catch(e){status(e.message,true);}};
$('#restore').onchange=async e=>{try{const file=e.target.files[0];if(!file)return;if(file.size>8*1024*1024)throw new Error('ไฟล์ต้องไม่เกิน 8 MB');const next=JSON.parse(await file.text());const errors=validateDB(next,catalog,vocabulary);if(errors.length)throw new Error(errors.join('\n'));if(!confirm('แทนที่ข้อมูลทุกแอปในเครื่องด้วย '+next.records.length+' รายการ และ '+next.ideas.length+' ไอเดีย? ควรสำรองข้อมูลเดิมก่อน'))return;const blocked=storageBlocked;storageBlocked=false;try{commit(next);}catch(err){storageBlocked=blocked;throw err;}status('นำเข้าข้อมูลสำเร็จ');}catch(err){status('นำเข้าไม่สำเร็จ: '+err.message,true);}finally{e.target.value='';}};
let view={x:0,y:0,w:900,h:520};const SVG='http://www.w3.org/2000/svg';function svg(tag,attrs){const e=document.createElementNS(SVG,tag);for(const [k,v] of Object.entries(attrs))e.setAttribute(k,v);return e;}
function drawGraph(){const network=$('#network');network.replaceChildren();view={x:0,y:0,w:900,h:520};network.setAttribute('viewBox','0 0 900 520');const graphIDs=new Set(scopedRecords().map(r=>r.id));const graphIdeas=scopedIdeas();for(const idea of graphIdeas)for(const id of idea.assets)graphIDs.add(id);for(const r of scopedRecords()){for(const key of ['model','edition','releaseGroup','inEdition','parent','participant'])if(r[key])graphIDs.add(r[key]);for(const o of r.observations)if(o.type==='reference'&&o.status==='known')graphIDs.add(o.value);}const nodes=[...db.records.filter(r=>graphIDs.has(r.id)).map(r=>({...r,color:'#9abe94'})),...graphIdeas.flatMap(r=>[{...r,color:'#e4a36f'}, {id:r.id+':mission',title:r.mission,color:'#baa6df',kind:'Mission'}])];const positions=new Map(nodes.map((n,i)=>[n.id,{x:450+Math.cos(i*2*Math.PI/Math.max(1,nodes.length))*Math.min(330,100+nodes.length*12),y:260+Math.sin(i*2*Math.PI/Math.max(1,nodes.length))*190}]));const edges=[];for(const r of db.records){for(const key of ['model','edition','releaseGroup','inEdition','parent','participant'])if(r[key])edges.push([r.id,r[key],false]);for(const o of r.observations)if(o.status==='known'&&o.type==='reference')edges.push([r.id,o.value,false]);}for(const r of db.ideas){edges.push([r.id,r.id+':mission',false]);for(const a of r.assets)edges.push([a,r.id,true]);}for(const [s,o,proposal] of edges){const a=positions.get(s),b=positions.get(o);if(!a||!b)continue;network.append(svg('line',{x1:a.x,y1:a.y,x2:b.x,y2:b.y,stroke:proposal?'#be9777':'#5a7d70','stroke-width':1.5,'stroke-dasharray':proposal?'5 5':'0'}));}
 let list=$('#node-list');if(!list){list=el('div');list.id='node-list';$('#graph-detail').replaceChildren(el('h3','เลือกโหนดเพื่อดูรายละเอียด'),el('p','เส้นประ = ข้อเสนอแรงบันดาลใจ'),list);}list.replaceChildren();const select=n=>{const detail=$('#graph-detail');detail.replaceChildren(el('h3',n.title),el('p',n.kind==='Mission'?'Mission':kinds[n.kind]||'ข้อเสนอสร้างสรรค์'),el('p',n.sourceText||n.mission||''));if(n.observations)for(const o of n.observations)detail.append(el('p',(fieldByID(o.field)?.label_th||o.field)+': '+(o.status==='known'?o.value+' '+o.unit:o.status)));const neighbors=edges.filter(([s,o])=>s===n.id||o===n.id);if(neighbors.length)detail.append(el('h3','เชื่อมโยงกับ'));for(const [s,o,proposal] of neighbors){const other=nodes.find(x=>x.id===(s===n.id?o:s));if(other){const go=el('button',other.title+(proposal?' · ไอเดียที่เสนอ':''));go.onclick=()=>select(other);detail.append(go);}}const reset=el('button','กลับสู่รายการทั้งหมด');reset.onclick=()=>{detail.replaceChildren(el('h3','เลือกโหนดเพื่อดูรายละเอียด'),el('p','เส้นประ = ข้อเสนอแรงบันดาลใจ'),el('div',undefined));detail.lastChild.id='node-list';drawGraph();};detail.append(reset);};
 for(const n of nodes){const p=positions.get(n.id),g=svg('g',{tabindex:0,role:'button','aria-label':n.title});g.append(svg('circle',{cx:p.x,cy:p.y,r:11,fill:n.color,stroke:'#d9e5c5','stroke-width':1}));const text=svg('text',{x:p.x,y:p.y+27,'text-anchor':'middle'});text.textContent=n.title.length>23?n.title.slice(0,23)+'…':n.title;g.append(text);g.onclick=()=>select(n);g.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();select(n);}};network.append(g);const b=el('button',n.title);b.onclick=()=>select(n);list.append(b);}
 if(!nodes.length){const text=svg('text',{x:450,y:260,'text-anchor':'middle'});text.textContent='เพิ่มรายการ แล้วความเชื่อมโยงจะปรากฏที่นี่';network.append(text);}
}
$('#reset-graph').onclick=drawGraph;
$('#network').addEventListener('wheel',e=>{e.preventDefault();const f=e.deltaY>0?1.12:.89;if(view.w*f<180||view.w*f>3600)return;view.x+=(view.w-view.w*f)/2;view.y+=(view.h-view.h*f)/2;view.w*=f;view.h*=f;$('#network').setAttribute('viewBox',`${view.x} ${view.y} ${view.w} ${view.h}`);},{passive:false});
let drag=null;$('#network').onpointerdown=e=>{if(e.target.closest('g'))return;drag={x:e.clientX,y:e.clientY};e.currentTarget.setPointerCapture(e.pointerId);};$('#network').onpointermove=e=>{if(!drag)return;const rect=e.currentTarget.getBoundingClientRect();view.x-=(e.clientX-drag.x)*view.w/rect.width;view.y-=(e.clientY-drag.y)*view.h/rect.height;drag={x:e.clientX,y:e.clientY};e.currentTarget.setAttribute('viewBox',`${view.x} ${view.y} ${view.w} ${view.h}`);};$('#network').onpointerup=$('#network').onpointercancel=()=>drag=null;
try{
 [catalog,vocabulary,thesaurus,taxonomy]=await Promise.all(['field-catalog.json','controlled-vocabulary.json','thesaurus.json','taxonomy.json'].map(async f=>{const r=await fetch('./standards/'+f);if(!r.ok)throw new Error('โหลดข้อกำหนดไม่สำเร็จ');return r.json();}));
 setupApp();
 fields=catalog.profiles.flatMap(p=>p.fields.map(f=>({...f,group:p.id,key:p.id+'.'+f.id})));
 options($('#record-domain'),Object.entries(domains).map(([k,v])=>[k,v.name]),'คลังกลาง / ยังไม่จัดแอป');options($('#concept-category'),taxonomy.collections.map(c=>[c.id,c.label]),'ทุกหมวด');options($('#kind'),Object.entries(kinds));options($('#profile'),Object.entries(profiles));
 const saved=localStorage.getItem(KEY);loadedSnapshot=saved;if(saved){try{const parsed=JSON.parse(saved);const errors=validateDB(parsed,catalog,vocabulary);if(errors.length)throw new Error(errors.join('\n'));db=parsed;}catch(e){storageBlocked=true;status('ข้อมูลเดิมอ่านไม่ได้และยังไม่ถูกเขียนทับ: '+e.message,true);}}
 for(const selector of ['#new-record','#backup','#restore','#export'])$(selector).disabled=false;
 $('#save-state').textContent='CV 1.1.1 · Metadata 1.3.0 · Ontology 1.0.0';render();
}catch(e){status('เริ่มต้นไม่สำเร็จ: '+e.message+' กรุณาโหลดหน้าใหม่',true);$('#new-idea').disabled=true;}

function setupApp(){
 const nav=$('#app-switcher');for(const [key,label] of [['','คลังกลาง'],...Object.entries(domains).map(([k,v])=>[k,v.name])]){const a=el('a',label);a.href='/asset-studio/'+(key?key+'/':'');if(key===(activeDomain||''))a.setAttribute('aria-current','page');nav.append(a);}
 if(!app){for(const [key,value] of Object.entries(domains)){const a=el('a',undefined,'domain-launch');a.href='/asset-studio/'+key+'/';a.append(el('strong',value.name),el('span',value.subtitle),el('small','เปิดแอป →'));$('#domain-actions').append(a);}return;}
 document.title=app.name+' — Noppadol';$('.hero h1').replaceChildren(document.createTextNode(app.title),el('span',app.subtitle));$('.hero .lead').textContent=app.description;$('.hero .eyebrow').textContent=app.name.toUpperCase()+' / SEIZE THE DAY';$('#inventory h2').textContent=app.name;$('#inventory .section-head p').textContent=app.hint;$('#editor .eyebrow').textContent=app.name.toUpperCase();
 for(const preset of app.presets){const button=el('button',preset.label);button.onclick=()=>openRecord(null,preset);$('#domain-actions').append(button);}
 $('#search').placeholder=activeDomain==='records'?'ค้นชื่อแผ่นหรือฉบับเผยแพร่':activeDomain==='photography'?'ค้นกล้อง เลนส์ หรือรุ่น':'ค้นเครื่องมือ ใบตัด หรือชื่อรุ่น';
 $('#graph .section-head p').textContent='กราฟของแอปนี้ รวมรายการที่เชื่อมถึงกันข้ามแอป · เลือกโหนดเพื่อสำรวจ';
}
// Reflect another app tab's saves instead of silently overwriting stale shared data.
window.addEventListener('storage',event=>{if(event.key!==KEY)return;try{const next=event.newValue?JSON.parse(event.newValue):emptyDB();const errors=validateDB(next,catalog,vocabulary);if(errors.length)throw new Error(errors.join('\n'));db=next;loadedSnapshot=event.newValue;render();staleDraft=!!document.querySelector('dialog[open]');status(staleDraft?'อีกแอปมีการเปลี่ยนข้อมูล สิ่งที่คุณกำลังพิมพ์ยังอยู่ กรุณาคัดลอกไว้แล้วปิดและเปิดฟอร์มใหม่ก่อนบันทึก':'ข้อมูลอัปเดตจากอีกแอปแล้ว');}catch(e){storageBlocked=true;status('ข้อมูลจากอีกแท็บอ่านไม่ได้: '+e.message,true);}});
