// App boundaries are navigation/workflow metadata, not new ontology classes.
const preset=(label,kind,profile,concept,fields=[])=>({label,kind,profile,concept,fields});
export const domains={
 woodworking:{name:'Woodworking Workshop',title:'เครื่องมือที่รู้จักมือคุณ',subtitle:'ดูแลเครื่องมือ เก็บประสบการณ์งานไม้',description:'ทะเบียนเครื่องมือ ใบตัด และประวัติการดูแล พร้อมพื้นที่ต่อยอดความรู้จากการลงมือทำ',category:'asset-nav-woodworking',profiles:['hand_plane','chisel','component','generic'],kinds:['AssetItem','Component','ProductModel','BrandRecord','AgentRecord','AssetEvent'],empty:'เริ่มจากเครื่องมือที่คุณหยิบใช้บ่อย',hint:'กบไสไม้ สิ่ว เลื่อย หินลับคม และส่วนประกอบ เก็บข้อมูลเฉพาะที่ช่วยให้ใช้และดูแลได้ดีขึ้น',presets:[
 preset('กบไสไม้','AssetItem','hand_plane','hand-plane',['hand_plane.blade_width','hand_plane.blade_steel','hand_plane.primary_bevel_angle','hand_plane.bed_angle']),
 preset('สิ่ว','AssetItem','chisel','chisel',['chisel.blade_width','chisel.blade_steel','chisel.bevel_angle']),
 preset('เลื่อย','AssetItem','generic','saw',['common.condition']),preset('หินลับคม','AssetItem','generic','sharpening-stone',['common.special_features']),
 preset('ใบกบ / ชิ้นส่วน','Component','component','plane-blade',['common.condition']),preset('บันทึกใช้ / ลับคม','AssetEvent','generic',null,[])], highlights:['ความคมและมุมใบตัด','สภาพและการดูแล','บทเรียนจากการลงมือทำ']},
 records:{name:'Record Room',title:'ทุกแผ่นมีเรื่องให้ฟัง',subtitle:'คอลเลกชันเสียง และบันทึกการฟัง',description:'แยกแผ่นที่คุณถือครองจากฉบับเผยแพร่ สำรวจศิลปิน คนทำเสียง และเรื่องราวที่ทำให้อยากกลับมาฟัง',category:'asset-nav-music',profiles:['record_disc','generic'],kinds:['AssetItem','ReleaseEdition','ReleaseGroup','TrackEntry','BrandRecord','AgentRecord','AssetEvent'],empty:'เริ่มต้นด้วยแผ่นที่คุณอยากเปิดฟัง',hint:'เพิ่มฉบับเผยแพร่ก่อน แล้วเชื่อมแผ่นที่ถือครองเข้ากับฉบับนั้น เก็บสภาพแผ่นแยกจากรายละเอียดฉบับ',presets:[
 preset('แผ่นที่ถือครอง','AssetItem','record_disc','record-disc',['record_disc.media_condition','record_disc.sleeve_condition','record_disc.copy_features']),
 preset('ฉบับเผยแพร่','ReleaseEdition','record_disc',null,['record_disc.release_title','record_disc.artist_credits','record_disc.engineering_credits','record_disc.label_catalog_entries','record_disc.playback_speed']),
 preset('กลุ่มฉบับ / Master','ReleaseGroup','record_disc',null,['record_disc.discogs_master_ref']),preset('แทร็ก','TrackEntry','record_disc',null,[]),preset('บันทึกการฟัง','AssetEvent','generic',null,[])], highlights:['แผ่นจริง → ฉบับ → กลุ่มฉบับ','ศิลปินและทีมเบื้องหลัง','ฟังแล้วได้ไอเดียอะไร']},
 photography:{name:'Camera Cabinet',title:'อุปกรณ์ที่พาไปเห็นโลก',subtitle:'กล้อง เลนส์ และประสบการณ์ถ่ายภาพ',description:'จัดการกล้องและเลนส์เป็นรายชิ้น เก็บข้อมูลการใช้งาน และเปลี่ยนประสบการณ์หลังกล้องให้เป็นเรื่องราว',category:'asset-nav-photography',profiles:['camera','component','generic'],kinds:['AssetItem','Component','ProductModel','BrandRecord','AgentRecord','AssetEvent'],empty:'เริ่มจากกล้องหรือเลนส์คู่ใจ',hint:'กล้องและเลนส์เป็นคนละรายการ เลือกอ้างอิงเลนส์ที่ติดตั้งเมื่อมีข้อมูล ไม่เหมารวมว่าทุกเลนส์ใช้ร่วมกันได้',presets:[
 preset('กล้อง','AssetItem','camera','camera',['camera.capture_medium','camera.lens_mount','camera.installed_lens']),
 preset('เลนส์','AssetItem','camera','lens',['camera.focal_length','camera.maximum_aperture','camera.lens_mount']),
 preset('อุปกรณ์เสริม','AssetItem','generic',null,['common.model','common.condition']),preset('รุ่นกล้อง / เลนส์','ProductModel','camera',null,['common.brand','common.model']),preset('บันทึกถ่ายภาพ / ดูแล','AssetEvent','generic',null,[])],highlights:['กล้องและเลนส์แยกรายชิ้น','การติดตั้งที่มีข้อมูลรองรับ','จากภาพที่ถ่ายสู่เรื่องที่เล่า']}
};
export function domainOf(r){if(r.domain)return r.domain;if(['hand_plane','chisel'].includes(r.profile))return 'woodworking';if(r.profile==='record_disc')return 'records';if(r.profile==='camera')return 'photography';return null;}
export function domainRecords(db,domain){return domain?db.records.filter(r=>domainOf(r)===domain):db.records;}
export function domainIdeas(db,domain){if(!domain)return db.ideas;const ids=new Set(domainRecords(db,domain).map(r=>r.id));return db.ideas.filter(i=>i.assets.some(id=>ids.has(id)));}
