// Complete dataset covering Liverpool FC from 1892 to 2026

const seasonsData = [
  {
    "season": "1892\u201393",
    "division": "Lancs \u2191",
    "played": 22,
    "won": 17,
    "drawn": 2,
    "lost": 3,
    "gf": 66,
    "ga": 19,
    "pts": 36,
    "pos": 1,
    "faCup": "QR3",
    "leagueCup": "\u2014",
    "commShield": "\u2014",
    "championsLeague": "\u2014",
    "europaLeague": "\u2014",
    "superCup": "\u2014",
    "clubWorldCup": "\u2014",
    "topScorer": "John Miller",
    "topScorerGoals": 25,
    "manager": "W. E. Barclay / John McKenna",
    "highlight": "Silverware won: Lancashire League Title. Inaugural season for Liverpool FC! Playing in the Lancashire League, they went unbeaten to secure their first-ever league title and earn promotion.",
    "majorTrophies": [
      "Lancashire League Title"
    ]
  },
  {
    "season": "1893\u201394",
    "division": "Division 2 \u2191",
    "played": 28,
    "won": 22,
    "drawn": 6,
    "lost": 0,
    "gf": 77,
    "ga": 18,
    "pts": 50,
    "pos": 1,
    "faCup": "R3",
    "leagueCup": "\u2014",
    "commShield": "\u2014",
    "championsLeague": "\u2014",
    "europaLeague": "\u2014",
    "superCup": "\u2014",
    "clubWorldCup": "\u2014",
    "topScorer": "James Stott",
    "topScorerGoals": 14,
    "manager": "W. E. Barclay / John McKenna",
    "highlight": "Finished 1st in the Division 2 \u2191 under manager W. E. Barclay / John McKenna. Top scorer James Stott scored 14 goals.",
    "majorTrophies": []
  },
  {
    "season": "1894\u201395",
    "division": "Division 1 \u2193",
    "played": 30,
    "won": 7,
    "drawn": 8,
    "lost": 15,
    "gf": 51,
    "ga": 70,
    "pts": 22,
    "pos": 16,
    "faCup": "R2",
    "leagueCup": "\u2014",
    "commShield": "\u2014",
    "championsLeague": "\u2014",
    "europaLeague": "\u2014",
    "superCup": "\u2014",
    "clubWorldCup": "\u2014",
    "topScorer": "Thomas Bradshaw",
    "topScorerGoals": 18,
    "manager": "W. E. Barclay / John McKenna",
    "highlight": "Finished 16th in the Division 1 \u2193 under manager W. E. Barclay / John McKenna. Top scorer Thomas Bradshaw scored 18 goals.",
    "majorTrophies": []
  },
  {
    "season": "1895\u201396",
    "division": "Division 2 \u2191",
    "played": 30,
    "won": 22,
    "drawn": 2,
    "lost": 6,
    "gf": 106,
    "ga": 32,
    "pts": 46,
    "pos": 1,
    "faCup": "R2",
    "leagueCup": "\u2014",
    "commShield": "\u2014",
    "championsLeague": "\u2014",
    "europaLeague": "\u2014",
    "superCup": "\u2014",
    "clubWorldCup": "\u2014",
    "topScorer": "George Allan",
    "topScorerGoals": 29,
    "manager": "W. E. Barclay / John McKenna",
    "highlight": "Finished 1st in the Division 2 \u2191 under manager W. E. Barclay / John McKenna. Top scorer George Allan scored 29 goals.",
    "majorTrophies": []
  },
  {
    "season": "1896\u201397",
    "division": "Division 1",
    "played": 30,
    "won": 12,
    "drawn": 9,
    "lost": 9,
    "gf": 46,
    "ga": 38,
    "pts": 33,
    "pos": 5,
    "faCup": "SF",
    "leagueCup": "\u2014",
    "commShield": "\u2014",
    "championsLeague": "\u2014",
    "europaLeague": "\u2014",
    "superCup": "\u2014",
    "clubWorldCup": "\u2014",
    "topScorer": "George Allan",
    "topScorerGoals": 18,
    "manager": "Tom Watson",
    "highlight": "Finished 5th in the Division 1 under manager Tom Watson. Top scorer George Allan scored 18 goals.",
    "majorTrophies": []
  },
  {
    "season": "1897\u201398",
    "division": "Division 1",
    "played": 30,
    "won": 11,
    "drawn": 6,
    "lost": 13,
    "gf": 48,
    "ga": 45,
    "pts": 28,
    "pos": 9,
    "faCup": "R3",
    "leagueCup": "\u2014",
    "commShield": "\u2014",
    "championsLeague": "\u2014",
    "europaLeague": "\u2014",
    "superCup": "\u2014",
    "clubWorldCup": "\u2014",
    "topScorer": "Frank Becton",
    "topScorerGoals": 13,
    "manager": "Tom Watson",
    "highlight": "Finished 9th in the Division 1 under manager Tom Watson. Top scorer Frank Becton scored 13 goals.",
    "majorTrophies": []
  },
  {
    "season": "1898\u201399",
    "division": "Division 1",
    "played": 34,
    "won": 19,
    "drawn": 5,
    "lost": 10,
    "gf": 49,
    "ga": 33,
    "pts": 43,
    "pos": 2,
    "faCup": "SF",
    "leagueCup": "\u2014",
    "commShield": "\u2014",
    "championsLeague": "\u2014",
    "europaLeague": "\u2014",
    "superCup": "\u2014",
    "clubWorldCup": "\u2014",
    "topScorer": "Hugh Morgan",
    "topScorerGoals": 13,
    "manager": "Tom Watson",
    "highlight": "Finished 2nd in the Division 1 under manager Tom Watson. Top scorer Hugh Morgan scored 13 goals.",
    "majorTrophies": []
  },
  {
    "season": "1900\u201301",
    "division": "Division 1",
    "played": 34,
    "won": 19,
    "drawn": 7,
    "lost": 8,
    "gf": 59,
    "ga": 35,
    "pts": 45,
    "pos": 1,
    "faCup": "R1",
    "leagueCup": "\u2014",
    "commShield": "\u2014",
    "championsLeague": "\u2014",
    "europaLeague": "\u2014",
    "superCup": "\u2014",
    "clubWorldCup": "\u2014",
    "topScorer": "Sam Raybould",
    "topScorerGoals": 18,
    "manager": "Tom Watson",
    "highlight": "Silverware won: League Title. Liverpool won the First Division for the first time in club history, edging out Sunderland by two points.",
    "majorTrophies": [
      "League Title"
    ]
  },
  {
    "season": "1901\u201302",
    "division": "Division 1",
    "played": 34,
    "won": 10,
    "drawn": 12,
    "lost": 12,
    "gf": 42,
    "ga": 38,
    "pts": 32,
    "pos": 11,
    "faCup": "R2",
    "leagueCup": "\u2014",
    "commShield": "\u2014",
    "championsLeague": "\u2014",
    "europaLeague": "\u2014",
    "superCup": "\u2014",
    "clubWorldCup": "\u2014",
    "topScorer": "Sam Raybould",
    "topScorerGoals": 18,
    "manager": "Tom Watson",
    "highlight": "Finished 11th in the Division 1 under manager Tom Watson. Top scorer Sam Raybould scored 18 goals.",
    "majorTrophies": []
  },
  {
    "season": "1902\u201303",
    "division": "Division 1",
    "played": 34,
    "won": 17,
    "drawn": 4,
    "lost": 13,
    "gf": 68,
    "ga": 49,
    "pts": 38,
    "pos": 5,
    "faCup": "R1",
    "leagueCup": "\u2014",
    "commShield": "\u2014",
    "championsLeague": "\u2014",
    "europaLeague": "\u2014",
    "superCup": "\u2014",
    "clubWorldCup": "\u2014",
    "topScorer": "Sam Raybould",
    "topScorerGoals": 32,
    "manager": "Tom Watson",
    "highlight": "Finished 5th in the Division 1 under manager Tom Watson. Top scorer Sam Raybould scored 32 goals.",
    "majorTrophies": []
  },
  {
    "season": "1903\u201304",
    "division": "Division 1 \u2193",
    "played": 34,
    "won": 9,
    "drawn": 8,
    "lost": 17,
    "gf": 49,
    "ga": 62,
    "pts": 26,
    "pos": 17,
    "faCup": "R1",
    "leagueCup": "\u2014",
    "commShield": "\u2014",
    "championsLeague": "\u2014",
    "europaLeague": "\u2014",
    "superCup": "\u2014",
    "clubWorldCup": "\u2014",
    "topScorer": "Jack Cox",
    "topScorerGoals": 9,
    "manager": "Tom Watson",
    "highlight": "Finished 17th in the Division 1 \u2193 under manager Tom Watson. Top scorer Jack Cox scored 9 goals.",
    "majorTrophies": []
  },
  {
    "season": "1904\u201305",
    "division": "Division 2 \u2191",
    "played": 34,
    "won": 27,
    "drawn": 4,
    "lost": 3,
    "gf": 93,
    "ga": 25,
    "pts": 58,
    "pos": 1,
    "faCup": "R1",
    "leagueCup": "\u2014",
    "commShield": "\u2014",
    "championsLeague": "\u2014",
    "europaLeague": "\u2014",
    "superCup": "\u2014",
    "clubWorldCup": "\u2014",
    "topScorer": "Robbie Robinson",
    "topScorerGoals": 23,
    "manager": "Tom Watson",
    "highlight": "Finished 1st in the Division 2 \u2191 under manager Tom Watson. Top scorer Robbie Robinson scored 23 goals.",
    "majorTrophies": []
  },
  {
    "season": "1905\u201306",
    "division": "Division 1",
    "played": 38,
    "won": 23,
    "drawn": 5,
    "lost": 10,
    "gf": 79,
    "ga": 46,
    "pts": 51,
    "pos": 1,
    "faCup": "SF",
    "leagueCup": "\u2014",
    "commShield": "\u2014",
    "championsLeague": "\u2014",
    "europaLeague": "\u2014",
    "superCup": "\u2014",
    "clubWorldCup": "\u2014",
    "topScorer": "Joe Hewitt",
    "topScorerGoals": 27,
    "manager": "Tom Watson",
    "highlight": "Silverware won: League Title. A historic double! Liverpool clinched their second First Division title, just one year after being promoted from the Second Division as champions.",
    "majorTrophies": [
      "League Title"
    ]
  },
  {
    "season": "1906\u201307",
    "division": "Division 1",
    "played": 38,
    "won": 13,
    "drawn": 7,
    "lost": 18,
    "gf": 64,
    "ga": 65,
    "pts": 33,
    "pos": 15,
    "faCup": "R4",
    "leagueCup": "\u2014",
    "commShield": "\u2014",
    "championsLeague": "\u2014",
    "europaLeague": "\u2014",
    "superCup": "\u2014",
    "clubWorldCup": "\u2014",
    "topScorer": "Sam Raybould",
    "topScorerGoals": 17,
    "manager": "Tom Watson",
    "highlight": "Finished 15th in the Division 1 under manager Tom Watson. Top scorer Sam Raybould scored 17 goals.",
    "majorTrophies": []
  },
  {
    "season": "1907\u201308",
    "division": "Division 1",
    "played": 38,
    "won": 16,
    "drawn": 6,
    "lost": 16,
    "gf": 68,
    "ga": 61,
    "pts": 38,
    "pos": 8,
    "faCup": "R3",
    "leagueCup": "\u2014",
    "commShield": "\u2014",
    "championsLeague": "\u2014",
    "europaLeague": "\u2014",
    "superCup": "\u2014",
    "clubWorldCup": "\u2014",
    "topScorer": "Joe Hewitt",
    "topScorerGoals": 22,
    "manager": "Tom Watson",
    "highlight": "Finished 8th in the Division 1 under manager Tom Watson. Top scorer Joe Hewitt scored 22 goals.",
    "majorTrophies": []
  },
  {
    "season": "1908\u201309",
    "division": "Division 1",
    "played": 38,
    "won": 15,
    "drawn": 6,
    "lost": 17,
    "gf": 57,
    "ga": 65,
    "pts": 36,
    "pos": 16,
    "faCup": "R2",
    "leagueCup": "\u2014",
    "commShield": "\u2014",
    "championsLeague": "\u2014",
    "europaLeague": "\u2014",
    "superCup": "\u2014",
    "clubWorldCup": "\u2014",
    "topScorer": "Ronald Orr",
    "topScorerGoals": 23,
    "manager": "Tom Watson",
    "highlight": "Finished 16th in the Division 1 under manager Tom Watson. Top scorer Ronald Orr scored 23 goals.",
    "majorTrophies": []
  },
  {
    "season": "1909\u201310",
    "division": "Division 1",
    "played": 38,
    "won": 21,
    "drawn": 6,
    "lost": 11,
    "gf": 78,
    "ga": 57,
    "pts": 48,
    "pos": 2,
    "faCup": "R1",
    "leagueCup": "\u2014",
    "commShield": "\u2014",
    "championsLeague": "\u2014",
    "europaLeague": "\u2014",
    "superCup": "\u2014",
    "clubWorldCup": "\u2014",
    "topScorer": "Jack Parkinson",
    "topScorerGoals": 30,
    "manager": "Tom Watson",
    "highlight": "Finished 2nd in the Division 1 under manager Tom Watson. Top scorer Jack Parkinson scored 30 goals.",
    "majorTrophies": []
  },
  {
    "season": "1910\u201311",
    "division": "Division 1",
    "played": 38,
    "won": 15,
    "drawn": 7,
    "lost": 16,
    "gf": 53,
    "ga": 53,
    "pts": 37,
    "pos": 13,
    "faCup": "R2",
    "leagueCup": "\u2014",
    "commShield": "\u2014",
    "championsLeague": "\u2014",
    "europaLeague": "\u2014",
    "superCup": "\u2014",
    "clubWorldCup": "\u2014",
    "topScorer": "Jack Parkinson",
    "topScorerGoals": 20,
    "manager": "Tom Watson",
    "highlight": "Finished 13th in the Division 1 under manager Tom Watson. Top scorer Jack Parkinson scored 20 goals.",
    "majorTrophies": []
  },
  {
    "season": "1911\u201312",
    "division": "Division 1",
    "played": 38,
    "won": 12,
    "drawn": 10,
    "lost": 16,
    "gf": 49,
    "ga": 55,
    "pts": 34,
    "pos": 17,
    "faCup": "R2",
    "leagueCup": "\u2014",
    "commShield": "\u2014",
    "championsLeague": "\u2014",
    "europaLeague": "\u2014",
    "superCup": "\u2014",
    "clubWorldCup": "\u2014",
    "topScorer": "Jack Parkinson",
    "topScorerGoals": 13,
    "manager": "Tom Watson",
    "highlight": "Finished 17th in the Division 1 under manager Tom Watson. Top scorer Jack Parkinson scored 13 goals.",
    "majorTrophies": []
  },
  {
    "season": "1912\u201313",
    "division": "Division 1",
    "played": 38,
    "won": 16,
    "drawn": 5,
    "lost": 17,
    "gf": 61,
    "ga": 71,
    "pts": 37,
    "pos": 12,
    "faCup": "R3",
    "leagueCup": "\u2014",
    "commShield": "\u2014",
    "championsLeague": "\u2014",
    "europaLeague": "\u2014",
    "superCup": "\u2014",
    "clubWorldCup": "\u2014",
    "topScorer": "Arthur Metcalf",
    "topScorerGoals": 18,
    "manager": "Tom Watson",
    "highlight": "Finished 12th in the Division 1 under manager Tom Watson. Top scorer Arthur Metcalf scored 18 goals.",
    "majorTrophies": []
  },
  {
    "season": "1913\u201314",
    "division": "Division 1",
    "played": 38,
    "won": 14,
    "drawn": 7,
    "lost": 17,
    "gf": 46,
    "ga": 62,
    "pts": 35,
    "pos": 16,
    "faCup": "RU",
    "leagueCup": "\u2014",
    "commShield": "\u2014",
    "championsLeague": "\u2014",
    "europaLeague": "\u2014",
    "superCup": "\u2014",
    "clubWorldCup": "\u2014",
    "topScorer": "Tom Miller",
    "topScorerGoals": 20,
    "manager": "Tom Watson",
    "highlight": "Finished 16th in the Division 1 under manager Tom Watson. Top scorer Tom Miller scored 20 goals.",
    "majorTrophies": []
  },
  {
    "season": "1914\u201315",
    "division": "Division 1",
    "played": 38,
    "won": 14,
    "drawn": 9,
    "lost": 15,
    "gf": 65,
    "ga": 75,
    "pts": 37,
    "pos": 13,
    "faCup": "R2",
    "leagueCup": "\u2014",
    "commShield": "\u2014",
    "championsLeague": "\u2014",
    "europaLeague": "\u2014",
    "superCup": "\u2014",
    "clubWorldCup": "\u2014",
    "topScorer": "Fred Pagnam",
    "topScorerGoals": 26,
    "manager": "Tom Watson",
    "highlight": "Finished 13th in the Division 1 under manager Tom Watson. Top scorer Fred Pagnam scored 26 goals.",
    "majorTrophies": []
  },
  {
    "season": "1919\u201320",
    "division": "Division 1",
    "played": 42,
    "won": 19,
    "drawn": 10,
    "lost": 13,
    "gf": 59,
    "ga": 44,
    "pts": 48,
    "pos": 4,
    "faCup": "R4",
    "leagueCup": "\u2014",
    "commShield": "\u2014",
    "championsLeague": "\u2014",
    "europaLeague": "\u2014",
    "superCup": "\u2014",
    "clubWorldCup": "\u2014",
    "topScorer": "Harry Chambers",
    "topScorerGoals": 15,
    "manager": "David Ashworth",
    "highlight": "Finished 4th in the Division 1 under manager David Ashworth. Top scorer Harry Chambers scored 15 goals.",
    "majorTrophies": []
  },
  {
    "season": "1920\u201321",
    "division": "Division 1",
    "played": 42,
    "won": 18,
    "drawn": 15,
    "lost": 9,
    "gf": 63,
    "ga": 35,
    "pts": 51,
    "pos": 4,
    "faCup": "R2",
    "leagueCup": "\u2014",
    "commShield": "\u2014",
    "championsLeague": "\u2014",
    "europaLeague": "\u2014",
    "superCup": "\u2014",
    "clubWorldCup": "\u2014",
    "topScorer": "Harry Chambers",
    "topScorerGoals": 24,
    "manager": "David Ashworth",
    "highlight": "Finished 4th in the Division 1 under manager David Ashworth. Top scorer Harry Chambers scored 24 goals.",
    "majorTrophies": []
  },
  {
    "season": "1921\u201322",
    "division": "Division 1",
    "played": 42,
    "won": 22,
    "drawn": 13,
    "lost": 7,
    "gf": 63,
    "ga": 36,
    "pts": 57,
    "pos": 1,
    "faCup": "R2",
    "leagueCup": "\u2014",
    "commShield": "\u2014",
    "championsLeague": "\u2014",
    "europaLeague": "\u2014",
    "superCup": "\u2014",
    "clubWorldCup": "\u2014",
    "topScorer": "Harry Chambers",
    "topScorerGoals": 21,
    "manager": "David Ashworth",
    "highlight": "Silverware won: League Title. Finished 1st in the Division 1 under manager David Ashworth. Top scorer Harry Chambers scored 21 goals.",
    "majorTrophies": [
      "League Title"
    ]
  },
  {
    "season": "1922\u201323",
    "division": "Division 1",
    "played": 42,
    "won": 26,
    "drawn": 8,
    "lost": 8,
    "gf": 70,
    "ga": 31,
    "pts": 60,
    "pos": 1,
    "faCup": "R3",
    "leagueCup": "\u2014",
    "commShield": "RU",
    "championsLeague": "\u2014",
    "europaLeague": "\u2014",
    "superCup": "\u2014",
    "clubWorldCup": "\u2014",
    "topScorer": "Harry Chambers",
    "topScorerGoals": 25,
    "manager": "David Ashworth / Matt McQueen",
    "highlight": "Silverware won: League Title. Finished 1st in the Division 1 under manager David Ashworth / Matt McQueen. Top scorer Harry Chambers scored 25 goals.",
    "majorTrophies": [
      "League Title"
    ]
  },
  {
    "season": "1923\u201324",
    "division": "Division 1",
    "played": 42,
    "won": 15,
    "drawn": 11,
    "lost": 16,
    "gf": 49,
    "ga": 48,
    "pts": 41,
    "pos": 12,
    "faCup": "R4",
    "leagueCup": "\u2014",
    "commShield": "\u2014",
    "championsLeague": "\u2014",
    "europaLeague": "\u2014",
    "superCup": "\u2014",
    "clubWorldCup": "\u2014",
    "topScorer": "Jimmy Walsh",
    "topScorerGoals": 19,
    "manager": "Matt McQueen",
    "highlight": "Finished 12th in the Division 1 under manager Matt McQueen. Top scorer Jimmy Walsh scored 19 goals.",
    "majorTrophies": []
  },
  {
    "season": "1924\u201325",
    "division": "Division 1",
    "played": 42,
    "won": 20,
    "drawn": 10,
    "lost": 12,
    "gf": 63,
    "ga": 55,
    "pts": 50,
    "pos": 4,
    "faCup": "R4",
    "leagueCup": "\u2014",
    "commShield": "\u2014",
    "championsLeague": "\u2014",
    "europaLeague": "\u2014",
    "superCup": "\u2014",
    "clubWorldCup": "\u2014",
    "topScorer": "Dick Forshaw",
    "topScorerGoals": 19,
    "manager": "Matt McQueen",
    "highlight": "Finished 4th in the Division 1 under manager Matt McQueen. Top scorer Dick Forshaw scored 19 goals.",
    "majorTrophies": []
  },
  {
    "season": "1925\u201326",
    "division": "Division 1",
    "played": 42,
    "won": 14,
    "drawn": 16,
    "lost": 12,
    "gf": 70,
    "ga": 63,
    "pts": 44,
    "pos": 7,
    "faCup": "R4",
    "leagueCup": "\u2014",
    "commShield": "\u2014",
    "championsLeague": "\u2014",
    "europaLeague": "\u2014",
    "superCup": "\u2014",
    "clubWorldCup": "\u2014",
    "topScorer": "Dick Forshaw",
    "topScorerGoals": 29,
    "manager": "Matt McQueen",
    "highlight": "Finished 7th in the Division 1 under manager Matt McQueen. Top scorer Dick Forshaw scored 29 goals.",
    "majorTrophies": []
  },
  {
    "season": "1926\u201327",
    "division": "Division 1",
    "played": 42,
    "won": 18,
    "drawn": 7,
    "lost": 17,
    "gf": 69,
    "ga": 61,
    "pts": 43,
    "pos": 9,
    "faCup": "R5",
    "leagueCup": "\u2014",
    "commShield": "\u2014",
    "championsLeague": "\u2014",
    "europaLeague": "\u2014",
    "superCup": "\u2014",
    "clubWorldCup": "\u2014",
    "topScorer": "Harry Chambers",
    "topScorerGoals": 21,
    "manager": "Matt McQueen",
    "highlight": "Finished 9th in the Division 1 under manager Matt McQueen. Top scorer Harry Chambers scored 21 goals.",
    "majorTrophies": []
  },
  {
    "season": "1927\u201328",
    "division": "Division 1",
    "played": 42,
    "won": 13,
    "drawn": 13,
    "lost": 16,
    "gf": 84,
    "ga": 87,
    "pts": 39,
    "pos": 16,
    "faCup": "R4",
    "leagueCup": "\u2014",
    "commShield": "\u2014",
    "championsLeague": "\u2014",
    "europaLeague": "\u2014",
    "superCup": "\u2014",
    "clubWorldCup": "\u2014",
    "topScorer": "Gordon Hodgson",
    "topScorerGoals": 23,
    "manager": "Matt McQueen",
    "highlight": "Finished 16th in the Division 1 under manager Matt McQueen. Top scorer Gordon Hodgson scored 23 goals.",
    "majorTrophies": []
  },
  {
    "season": "1928\u201329",
    "division": "Division 1",
    "played": 42,
    "won": 17,
    "drawn": 12,
    "lost": 13,
    "gf": 90,
    "ga": 64,
    "pts": 46,
    "pos": 5,
    "faCup": "R4",
    "leagueCup": "\u2014",
    "commShield": "\u2014",
    "championsLeague": "\u2014",
    "europaLeague": "\u2014",
    "superCup": "\u2014",
    "clubWorldCup": "\u2014",
    "topScorer": "Gordon Hodgson",
    "topScorerGoals": 32,
    "manager": "George Patterson",
    "highlight": "Finished 5th in the Division 1 under manager George Patterson. Top scorer Gordon Hodgson scored 32 goals.",
    "majorTrophies": []
  },
  {
    "season": "1929\u201330",
    "division": "Division 1",
    "played": 42,
    "won": 16,
    "drawn": 9,
    "lost": 17,
    "gf": 63,
    "ga": 79,
    "pts": 41,
    "pos": 12,
    "faCup": "R3",
    "leagueCup": "\u2014",
    "commShield": "\u2014",
    "championsLeague": "\u2014",
    "europaLeague": "\u2014",
    "superCup": "\u2014",
    "clubWorldCup": "\u2014",
    "topScorer": "Jimmy Smith",
    "topScorerGoals": 23,
    "manager": "George Patterson",
    "highlight": "Finished 12th in the Division 1 under manager George Patterson. Top scorer Jimmy Smith scored 23 goals.",
    "majorTrophies": []
  },
  {
    "season": "1930\u201331",
    "division": "Division 1",
    "played": 42,
    "won": 15,
    "drawn": 12,
    "lost": 15,
    "gf": 86,
    "ga": 85,
    "pts": 42,
    "pos": 9,
    "faCup": "R3",
    "leagueCup": "\u2014",
    "commShield": "\u2014",
    "championsLeague": "\u2014",
    "europaLeague": "\u2014",
    "superCup": "\u2014",
    "clubWorldCup": "\u2014",
    "topScorer": "Gordon Hodgson",
    "topScorerGoals": 36,
    "manager": "George Patterson",
    "highlight": "Finished 9th in the Division 1 under manager George Patterson. Top scorer Gordon Hodgson scored 36 goals.",
    "majorTrophies": []
  },
  {
    "season": "1931\u201332",
    "division": "Division 1",
    "played": 42,
    "won": 19,
    "drawn": 6,
    "lost": 17,
    "gf": 81,
    "ga": 93,
    "pts": 44,
    "pos": 10,
    "faCup": "R6",
    "leagueCup": "\u2014",
    "commShield": "\u2014",
    "championsLeague": "\u2014",
    "europaLeague": "\u2014",
    "superCup": "\u2014",
    "clubWorldCup": "\u2014",
    "topScorer": "Gordon Hodgson",
    "topScorerGoals": 27,
    "manager": "George Patterson",
    "highlight": "Finished 10th in the Division 1 under manager George Patterson. Top scorer Gordon Hodgson scored 27 goals.",
    "majorTrophies": []
  },
  {
    "season": "1932\u201333",
    "division": "Division 1",
    "played": 42,
    "won": 14,
    "drawn": 11,
    "lost": 17,
    "gf": 79,
    "ga": 84,
    "pts": 39,
    "pos": 14,
    "faCup": "R3",
    "leagueCup": "\u2014",
    "commShield": "\u2014",
    "championsLeague": "\u2014",
    "europaLeague": "\u2014",
    "superCup": "\u2014",
    "clubWorldCup": "\u2014",
    "topScorer": "Gordon Hodgson",
    "topScorerGoals": 24,
    "manager": "George Patterson",
    "highlight": "Finished 14th in the Division 1 under manager George Patterson. Top scorer Gordon Hodgson scored 24 goals.",
    "majorTrophies": []
  },
  {
    "season": "1933\u201334",
    "division": "Division 1",
    "played": 42,
    "won": 14,
    "drawn": 10,
    "lost": 18,
    "gf": 79,
    "ga": 87,
    "pts": 38,
    "pos": 18,
    "faCup": "R5",
    "leagueCup": "\u2014",
    "commShield": "\u2014",
    "championsLeague": "\u2014",
    "europaLeague": "\u2014",
    "superCup": "\u2014",
    "clubWorldCup": "\u2014",
    "topScorer": "Gordon Hodgson",
    "topScorerGoals": 25,
    "manager": "George Patterson",
    "highlight": "Finished 18th in the Division 1 under manager George Patterson. Top scorer Gordon Hodgson scored 25 goals.",
    "majorTrophies": []
  },
  {
    "season": "1934\u201335",
    "division": "Division 1",
    "played": 42,
    "won": 19,
    "drawn": 7,
    "lost": 16,
    "gf": 85,
    "ga": 88,
    "pts": 45,
    "pos": 7,
    "faCup": "R4",
    "leagueCup": "\u2014",
    "commShield": "\u2014",
    "championsLeague": "\u2014",
    "europaLeague": "\u2014",
    "superCup": "\u2014",
    "clubWorldCup": "\u2014",
    "topScorer": "Gordon Hodgson",
    "topScorerGoals": 29,
    "manager": "George Patterson",
    "highlight": "Finished 7th in the Division 1 under manager George Patterson. Top scorer Gordon Hodgson scored 29 goals.",
    "majorTrophies": []
  },
  {
    "season": "1935\u201336",
    "division": "Division 1",
    "played": 42,
    "won": 13,
    "drawn": 12,
    "lost": 17,
    "gf": 60,
    "ga": 64,
    "pts": 38,
    "pos": 19,
    "faCup": "R3",
    "leagueCup": "\u2014",
    "commShield": "\u2014",
    "championsLeague": "\u2014",
    "europaLeague": "\u2014",
    "superCup": "\u2014",
    "clubWorldCup": "\u2014",
    "topScorer": "Fred Howe",
    "topScorerGoals": 17,
    "manager": "George Patterson",
    "highlight": "Finished 19th in the Division 1 under manager George Patterson. Top scorer Fred Howe scored 17 goals.",
    "majorTrophies": []
  },
  {
    "season": "1936\u201337",
    "division": "Division 1",
    "played": 42,
    "won": 12,
    "drawn": 11,
    "lost": 19,
    "gf": 62,
    "ga": 84,
    "pts": 35,
    "pos": 18,
    "faCup": "R3",
    "leagueCup": "\u2014",
    "commShield": "\u2014",
    "championsLeague": "\u2014",
    "europaLeague": "\u2014",
    "superCup": "\u2014",
    "clubWorldCup": "\u2014",
    "topScorer": "Fred Howe",
    "topScorerGoals": 16,
    "manager": "George Kay",
    "highlight": "Finished 18th in the Division 1 under manager George Kay. Top scorer Fred Howe scored 16 goals.",
    "majorTrophies": []
  },
  {
    "season": "1937\u201338",
    "division": "Division 1",
    "played": 42,
    "won": 15,
    "drawn": 11,
    "lost": 16,
    "gf": 65,
    "ga": 71,
    "pts": 41,
    "pos": 11,
    "faCup": "R5",
    "leagueCup": "\u2014",
    "commShield": "\u2014",
    "championsLeague": "\u2014",
    "europaLeague": "\u2014",
    "superCup": "\u2014",
    "clubWorldCup": "\u2014",
    "topScorer": "Alf Hanson",
    "topScorerGoals": 15,
    "manager": "George Kay",
    "highlight": "Finished 11th in the Division 1 under manager George Kay. Top scorer Alf Hanson scored 15 goals.",
    "majorTrophies": []
  },
  {
    "season": "1938\u201339",
    "division": "Division 1",
    "played": 42,
    "won": 14,
    "drawn": 14,
    "lost": 14,
    "gf": 62,
    "ga": 63,
    "pts": 42,
    "pos": 11,
    "faCup": "R5",
    "leagueCup": "\u2014",
    "commShield": "\u2014",
    "championsLeague": "\u2014",
    "europaLeague": "\u2014",
    "superCup": "\u2014",
    "clubWorldCup": "\u2014",
    "topScorer": "Berry Nieuwenhuys",
    "topScorerGoals": 16,
    "manager": "George Kay",
    "highlight": "Finished 11th in the Division 1 under manager George Kay. Top scorer Berry Nieuwenhuys scored 16 goals.",
    "majorTrophies": []
  },
  {
    "season": "1945\u201346",
    "division": "\u2014",
    "played": 0,
    "won": 0,
    "drawn": 0,
    "lost": 0,
    "gf": 0,
    "ga": 0,
    "pts": 0,
    "pos": 0,
    "faCup": "R4",
    "leagueCup": "\u2014",
    "commShield": "\u2014",
    "championsLeague": "\u2014",
    "europaLeague": "\u2014",
    "superCup": "\u2014",
    "clubWorldCup": "\u2014",
    "topScorer": "Willie Fagan",
    "topScorerGoals": 3,
    "manager": "George Kay",
    "highlight": "Finished N/A in the \u2014 under manager George Kay. Top scorer Willie Fagan scored 3 goals.",
    "majorTrophies": []
  },
  {
    "season": "1946\u201347",
    "division": "Division 1",
    "played": 42,
    "won": 25,
    "drawn": 7,
    "lost": 10,
    "gf": 84,
    "ga": 52,
    "pts": 57,
    "pos": 1,
    "faCup": "SF",
    "leagueCup": "\u2014",
    "commShield": "\u2014",
    "championsLeague": "\u2014",
    "europaLeague": "\u2014",
    "superCup": "\u2014",
    "clubWorldCup": "\u2014",
    "topScorer": "Jack Balmer, Albert Stubbins",
    "topScorerGoals": 28,
    "manager": "George Kay",
    "highlight": "Silverware won: League Title. The first post-war football season ended in glory. A high-scoring team led by Jack Balmer and Albert Stubbins won Liverpool's fifth league championship.",
    "majorTrophies": [
      "League Title"
    ]
  },
  {
    "season": "1947\u201348",
    "division": "Division 1",
    "played": 42,
    "won": 16,
    "drawn": 10,
    "lost": 16,
    "gf": 65,
    "ga": 61,
    "pts": 42,
    "pos": 11,
    "faCup": "R5",
    "leagueCup": "\u2014",
    "commShield": "\u2014",
    "championsLeague": "\u2014",
    "europaLeague": "\u2014",
    "superCup": "\u2014",
    "clubWorldCup": "\u2014",
    "topScorer": "Albert Stubbins",
    "topScorerGoals": 26,
    "manager": "George Kay",
    "highlight": "Finished 11th in the Division 1 under manager George Kay. Top scorer Albert Stubbins scored 26 goals.",
    "majorTrophies": []
  },
  {
    "season": "1948\u201349",
    "division": "Division 1",
    "played": 42,
    "won": 13,
    "drawn": 14,
    "lost": 15,
    "gf": 53,
    "ga": 43,
    "pts": 40,
    "pos": 12,
    "faCup": "R5",
    "leagueCup": "\u2014",
    "commShield": "\u2014",
    "championsLeague": "\u2014",
    "europaLeague": "\u2014",
    "superCup": "\u2014",
    "clubWorldCup": "\u2014",
    "topScorer": "Jack Balmer",
    "topScorerGoals": 16,
    "manager": "George Kay",
    "highlight": "Finished 12th in the Division 1 under manager George Kay. Top scorer Jack Balmer scored 16 goals.",
    "majorTrophies": []
  },
  {
    "season": "1949\u201350",
    "division": "Division 1",
    "played": 42,
    "won": 17,
    "drawn": 14,
    "lost": 11,
    "gf": 64,
    "ga": 54,
    "pts": 48,
    "pos": 8,
    "faCup": "RU",
    "leagueCup": "\u2014",
    "commShield": "\u2014",
    "championsLeague": "\u2014",
    "europaLeague": "\u2014",
    "superCup": "\u2014",
    "clubWorldCup": "\u2014",
    "topScorer": "Billy Liddell",
    "topScorerGoals": 19,
    "manager": "George Kay",
    "highlight": "Finished 8th in the Division 1 under manager George Kay. Top scorer Billy Liddell scored 19 goals.",
    "majorTrophies": []
  },
  {
    "season": "1950\u201351",
    "division": "Division 1",
    "played": 42,
    "won": 16,
    "drawn": 11,
    "lost": 15,
    "gf": 53,
    "ga": 59,
    "pts": 43,
    "pos": 9,
    "faCup": "R3",
    "leagueCup": "\u2014",
    "commShield": "\u2014",
    "championsLeague": "\u2014",
    "europaLeague": "\u2014",
    "superCup": "\u2014",
    "clubWorldCup": "\u2014",
    "topScorer": "Billy Liddell",
    "topScorerGoals": 15,
    "manager": "George Kay",
    "highlight": "Finished 9th in the Division 1 under manager George Kay. Top scorer Billy Liddell scored 15 goals.",
    "majorTrophies": []
  },
  {
    "season": "1951\u201352",
    "division": "Division 1",
    "played": 42,
    "won": 12,
    "drawn": 19,
    "lost": 11,
    "gf": 57,
    "ga": 61,
    "pts": 43,
    "pos": 11,
    "faCup": "R5",
    "leagueCup": "\u2014",
    "commShield": "\u2014",
    "championsLeague": "\u2014",
    "europaLeague": "\u2014",
    "superCup": "\u2014",
    "clubWorldCup": "\u2014",
    "topScorer": "Billy Liddell",
    "topScorerGoals": 19,
    "manager": "Don Welsh",
    "highlight": "Finished 11th in the Division 1 under manager Don Welsh. Top scorer Billy Liddell scored 19 goals.",
    "majorTrophies": []
  },
  {
    "season": "1952\u201353",
    "division": "Division 1",
    "played": 42,
    "won": 14,
    "drawn": 8,
    "lost": 20,
    "gf": 61,
    "ga": 82,
    "pts": 36,
    "pos": 17,
    "faCup": "R3",
    "leagueCup": "\u2014",
    "commShield": "\u2014",
    "championsLeague": "\u2014",
    "europaLeague": "\u2014",
    "superCup": "\u2014",
    "clubWorldCup": "\u2014",
    "topScorer": "Billy Liddell",
    "topScorerGoals": 13,
    "manager": "Don Welsh",
    "highlight": "Finished 17th in the Division 1 under manager Don Welsh. Top scorer Billy Liddell scored 13 goals.",
    "majorTrophies": []
  },
  {
    "season": "1953\u201354",
    "division": "Division 1 \u2193",
    "played": 42,
    "won": 9,
    "drawn": 10,
    "lost": 23,
    "gf": 68,
    "ga": 97,
    "pts": 28,
    "pos": 22,
    "faCup": "R3",
    "leagueCup": "\u2014",
    "commShield": "\u2014",
    "championsLeague": "\u2014",
    "europaLeague": "\u2014",
    "superCup": "\u2014",
    "clubWorldCup": "\u2014",
    "topScorer": "Sammy Smyth",
    "topScorerGoals": 13,
    "manager": "Don Welsh",
    "highlight": "Finished 22th in the Division 1 \u2193 under manager Don Welsh. Top scorer Sammy Smyth scored 13 goals.",
    "majorTrophies": []
  },
  {
    "season": "1954\u201355",
    "division": "Division 2",
    "played": 42,
    "won": 16,
    "drawn": 10,
    "lost": 16,
    "gf": 92,
    "ga": 96,
    "pts": 42,
    "pos": 11,
    "faCup": "R5",
    "leagueCup": "\u2014",
    "commShield": "\u2014",
    "championsLeague": "\u2014",
    "europaLeague": "\u2014",
    "superCup": "\u2014",
    "clubWorldCup": "\u2014",
    "topScorer": "John Evans",
    "topScorerGoals": 33,
    "manager": "Don Welsh",
    "highlight": "Finished 11th in the Division 2 under manager Don Welsh. Top scorer John Evans scored 33 goals.",
    "majorTrophies": []
  },
  {
    "season": "1955\u201356",
    "division": "Division 2",
    "played": 42,
    "won": 21,
    "drawn": 6,
    "lost": 15,
    "gf": 85,
    "ga": 63,
    "pts": 48,
    "pos": 3,
    "faCup": "R5",
    "leagueCup": "\u2014",
    "commShield": "\u2014",
    "championsLeague": "\u2014",
    "europaLeague": "\u2014",
    "superCup": "\u2014",
    "clubWorldCup": "\u2014",
    "topScorer": "Billy Liddell",
    "topScorerGoals": 32,
    "manager": "Don Welsh",
    "highlight": "Finished 3rd in the Division 2 under manager Don Welsh. Top scorer Billy Liddell scored 32 goals.",
    "majorTrophies": []
  },
  {
    "season": "1956\u201357",
    "division": "Division 2",
    "played": 42,
    "won": 21,
    "drawn": 11,
    "lost": 10,
    "gf": 82,
    "ga": 54,
    "pts": 53,
    "pos": 3,
    "faCup": "R3",
    "leagueCup": "\u2014",
    "commShield": "\u2014",
    "championsLeague": "\u2014",
    "europaLeague": "\u2014",
    "superCup": "\u2014",
    "clubWorldCup": "\u2014",
    "topScorer": "Billy Liddell",
    "topScorerGoals": 21,
    "manager": "Phil Taylor",
    "highlight": "Finished 3rd in the Division 2 under manager Phil Taylor. Top scorer Billy Liddell scored 21 goals.",
    "majorTrophies": []
  },
  {
    "season": "1957\u201358",
    "division": "Division 2",
    "played": 42,
    "won": 22,
    "drawn": 10,
    "lost": 10,
    "gf": 79,
    "ga": 54,
    "pts": 54,
    "pos": 4,
    "faCup": "R6",
    "leagueCup": "\u2014",
    "commShield": "\u2014",
    "championsLeague": "\u2014",
    "europaLeague": "\u2014",
    "superCup": "\u2014",
    "clubWorldCup": "\u2014",
    "topScorer": "Billy Liddell",
    "topScorerGoals": 23,
    "manager": "Phil Taylor",
    "highlight": "Finished 4th in the Division 2 under manager Phil Taylor. Top scorer Billy Liddell scored 23 goals.",
    "majorTrophies": []
  },
  {
    "season": "1958\u201359",
    "division": "Division 2",
    "played": 42,
    "won": 24,
    "drawn": 5,
    "lost": 13,
    "gf": 87,
    "ga": 62,
    "pts": 53,
    "pos": 4,
    "faCup": "R3",
    "leagueCup": "\u2014",
    "commShield": "\u2014",
    "championsLeague": "\u2014",
    "europaLeague": "\u2014",
    "superCup": "\u2014",
    "clubWorldCup": "\u2014",
    "topScorer": "Jimmy Melia",
    "topScorerGoals": 21,
    "manager": "Phil Taylor",
    "highlight": "Finished 4th in the Division 2 under manager Phil Taylor. Top scorer Jimmy Melia scored 21 goals.",
    "majorTrophies": []
  },
  {
    "season": "1959\u201360",
    "division": "Division 2",
    "played": 42,
    "won": 20,
    "drawn": 10,
    "lost": 12,
    "gf": 90,
    "ga": 66,
    "pts": 50,
    "pos": 3,
    "faCup": "R4",
    "leagueCup": "\u2014",
    "commShield": "\u2014",
    "championsLeague": "\u2014",
    "europaLeague": "\u2014",
    "superCup": "\u2014",
    "clubWorldCup": "\u2014",
    "topScorer": "Roger Hunt",
    "topScorerGoals": 23,
    "manager": "Phil Taylor / Bill Shankly",
    "highlight": "Finished 3rd in the Division 2 under manager Phil Taylor / Bill Shankly. Top scorer Roger Hunt scored 23 goals.",
    "majorTrophies": []
  },
  {
    "season": "1960\u201361",
    "division": "Division 2",
    "played": 42,
    "won": 21,
    "drawn": 10,
    "lost": 11,
    "gf": 87,
    "ga": 58,
    "pts": 52,
    "pos": 3,
    "faCup": "R4",
    "leagueCup": "R3",
    "commShield": "\u2014",
    "championsLeague": "\u2014",
    "europaLeague": "\u2014",
    "superCup": "\u2014",
    "clubWorldCup": "\u2014",
    "topScorer": "Kevin Lewis",
    "topScorerGoals": 32,
    "manager": "Bill Shankly",
    "highlight": "Finished 3rd in the Division 2 under manager Bill Shankly. Top scorer Kevin Lewis scored 32 goals.",
    "majorTrophies": []
  },
  {
    "season": "1961\u201362",
    "division": "Division 2 \u2191",
    "played": 42,
    "won": 27,
    "drawn": 8,
    "lost": 7,
    "gf": 99,
    "ga": 43,
    "pts": 62,
    "pos": 1,
    "faCup": "R5",
    "leagueCup": "\u2014",
    "commShield": "\u2014",
    "championsLeague": "\u2014",
    "europaLeague": "\u2014",
    "superCup": "\u2014",
    "clubWorldCup": "\u2014",
    "topScorer": "Roger Hunt",
    "topScorerGoals": 42,
    "manager": "Bill Shankly",
    "highlight": "Finished 1st in the Division 2 \u2191 under manager Bill Shankly. Top scorer Roger Hunt scored 42 goals.",
    "majorTrophies": []
  },
  {
    "season": "1962\u201363",
    "division": "Division 1",
    "played": 42,
    "won": 17,
    "drawn": 10,
    "lost": 15,
    "gf": 71,
    "ga": 59,
    "pts": 44,
    "pos": 8,
    "faCup": "SF",
    "leagueCup": "\u2014",
    "commShield": "\u2014",
    "championsLeague": "\u2014",
    "europaLeague": "\u2014",
    "superCup": "\u2014",
    "clubWorldCup": "\u2014",
    "topScorer": "Roger Hunt",
    "topScorerGoals": 26,
    "manager": "Bill Shankly",
    "highlight": "Finished 8th in the Division 1 under manager Bill Shankly. Top scorer Roger Hunt scored 26 goals.",
    "majorTrophies": []
  },
  {
    "season": "1963\u201364",
    "division": "Division 1",
    "played": 42,
    "won": 26,
    "drawn": 5,
    "lost": 11,
    "gf": 92,
    "ga": 45,
    "pts": 57,
    "pos": 1,
    "faCup": "R6",
    "leagueCup": "\u2014",
    "commShield": "\u2014",
    "championsLeague": "\u2014",
    "europaLeague": "\u2014",
    "superCup": "\u2014",
    "clubWorldCup": "\u2014",
    "topScorer": "Roger Hunt",
    "topScorerGoals": 33,
    "manager": "Bill Shankly",
    "highlight": "Silverware won: League Title. Under the legendary Bill Shankly, Liverpool won their first league title in 17 years, signaling the start of their dominance in modern English football.",
    "majorTrophies": [
      "League Title"
    ]
  },
  {
    "season": "1964\u201365",
    "division": "Division 1",
    "played": 42,
    "won": 17,
    "drawn": 10,
    "lost": 15,
    "gf": 67,
    "ga": 73,
    "pts": 44,
    "pos": 7,
    "faCup": "W",
    "leagueCup": "\u2014",
    "commShield": "W[h]",
    "championsLeague": "SF",
    "europaLeague": "\u2014",
    "superCup": "\u2014",
    "clubWorldCup": "\u2014",
    "topScorer": "Roger Hunt",
    "topScorerGoals": 37,
    "manager": "Bill Shankly",
    "highlight": "Silverware won: FA Cup, Community Shield. Finished 7th in the Division 1 under manager Bill Shankly. Top scorer Roger Hunt scored 37 goals.",
    "majorTrophies": [
      "FA Cup",
      "Community Shield"
    ]
  },
  {
    "season": "1965\u201366",
    "division": "Division 1",
    "played": 42,
    "won": 26,
    "drawn": 9,
    "lost": 7,
    "gf": 79,
    "ga": 34,
    "pts": 61,
    "pos": 1,
    "faCup": "R3",
    "leagueCup": "\u2014",
    "commShield": "W[h]",
    "championsLeague": "\u2014",
    "europaLeague": "\u2014",
    "superCup": "\u2014",
    "clubWorldCup": "\u2014",
    "topScorer": "Roger Hunt",
    "topScorerGoals": 33,
    "manager": "Bill Shankly",
    "highlight": "Silverware won: League Title, Community Shield. Bill Shankly led the team to their 7th First Division title and reached the final of the European Cup Winners' Cup, losing narrowly to Dortmund.",
    "majorTrophies": [
      "League Title",
      "Community Shield"
    ]
  },
  {
    "season": "1966\u201367",
    "division": "Division 1",
    "played": 42,
    "won": 19,
    "drawn": 13,
    "lost": 10,
    "gf": 64,
    "ga": 47,
    "pts": 51,
    "pos": 5,
    "faCup": "R5",
    "leagueCup": "\u2014",
    "commShield": "W",
    "championsLeague": "R2",
    "europaLeague": "\u2014",
    "superCup": "\u2014",
    "clubWorldCup": "\u2014",
    "topScorer": "Roger Hunt",
    "topScorerGoals": 19,
    "manager": "Bill Shankly",
    "highlight": "Silverware won: Community Shield. Finished 5th in the Division 1 under manager Bill Shankly. Top scorer Roger Hunt scored 19 goals.",
    "majorTrophies": [
      "Community Shield"
    ]
  },
  {
    "season": "1967\u201368",
    "division": "Division 1",
    "played": 42,
    "won": 22,
    "drawn": 11,
    "lost": 9,
    "gf": 71,
    "ga": 40,
    "pts": 55,
    "pos": 3,
    "faCup": "R6",
    "leagueCup": "R2",
    "commShield": "\u2014",
    "championsLeague": "\u2014",
    "europaLeague": "R3",
    "superCup": "\u2014",
    "clubWorldCup": "\u2014",
    "topScorer": "Roger Hunt",
    "topScorerGoals": 30,
    "manager": "Bill Shankly",
    "highlight": "Finished 3rd in the Division 1 under manager Bill Shankly. Top scorer Roger Hunt scored 30 goals.",
    "majorTrophies": []
  },
  {
    "season": "1968\u201369",
    "division": "Division 1",
    "played": 42,
    "won": 25,
    "drawn": 11,
    "lost": 6,
    "gf": 63,
    "ga": 24,
    "pts": 61,
    "pos": 2,
    "faCup": "R5",
    "leagueCup": "R4",
    "commShield": "\u2014",
    "championsLeague": "\u2014",
    "europaLeague": "R1",
    "superCup": "\u2014",
    "clubWorldCup": "\u2014",
    "topScorer": "Roger Hunt",
    "topScorerGoals": 17,
    "manager": "Bill Shankly",
    "highlight": "Finished 2nd in the Division 1 under manager Bill Shankly. Top scorer Roger Hunt scored 17 goals.",
    "majorTrophies": []
  },
  {
    "season": "1969\u201370",
    "division": "Division 1",
    "played": 42,
    "won": 20,
    "drawn": 11,
    "lost": 11,
    "gf": 65,
    "ga": 42,
    "pts": 51,
    "pos": 5,
    "faCup": "R6",
    "leagueCup": "R3",
    "commShield": "\u2014",
    "championsLeague": "\u2014",
    "europaLeague": "R2",
    "superCup": "\u2014",
    "clubWorldCup": "\u2014",
    "topScorer": "Bobby Graham",
    "topScorerGoals": 21,
    "manager": "Bill Shankly",
    "highlight": "Finished 5th in the Division 1 under manager Bill Shankly. Top scorer Bobby Graham scored 21 goals.",
    "majorTrophies": []
  },
  {
    "season": "1970\u201371",
    "division": "Division 1",
    "played": 42,
    "won": 17,
    "drawn": 17,
    "lost": 8,
    "gf": 42,
    "ga": 24,
    "pts": 51,
    "pos": 5,
    "faCup": "RU",
    "leagueCup": "R3",
    "commShield": "\u2014",
    "championsLeague": "\u2014",
    "europaLeague": "SF",
    "superCup": "\u2014",
    "clubWorldCup": "\u2014",
    "topScorer": "Alun Evans",
    "topScorerGoals": 15,
    "manager": "Bill Shankly",
    "highlight": "Finished 5th in the Division 1 under manager Bill Shankly. Top scorer Alun Evans scored 15 goals.",
    "majorTrophies": []
  },
  {
    "season": "1971\u201372",
    "division": "Division 1",
    "played": 42,
    "won": 24,
    "drawn": 9,
    "lost": 9,
    "gf": 64,
    "ga": 30,
    "pts": 57,
    "pos": 3,
    "faCup": "R4",
    "leagueCup": "R4",
    "commShield": "RU",
    "championsLeague": "\u2014",
    "europaLeague": "\u2014",
    "superCup": "\u2014",
    "clubWorldCup": "\u2014",
    "topScorer": "John Toshack",
    "topScorerGoals": 13,
    "manager": "Bill Shankly",
    "highlight": "Finished 3rd in the Division 1 under manager Bill Shankly. Top scorer John Toshack scored 13 goals.",
    "majorTrophies": []
  },
  {
    "season": "1972\u201373",
    "division": "Division 1",
    "played": 42,
    "won": 25,
    "drawn": 10,
    "lost": 7,
    "gf": 72,
    "ga": 42,
    "pts": 60,
    "pos": 1,
    "faCup": "R4",
    "leagueCup": "R5",
    "commShield": "\u2014",
    "championsLeague": "\u2014",
    "europaLeague": "W",
    "superCup": "\u2014",
    "clubWorldCup": "\u2014",
    "topScorer": "Kevin Keegan",
    "topScorerGoals": 22,
    "manager": "Bill Shankly",
    "highlight": "Silverware won: League Title, UEFA Cup. A magnificent double! Shankly guided Liverpool to the First Division title and their first-ever European trophy, defeating Borussia M\u00f6nchengladbach in the UEFA Cup.",
    "majorTrophies": [
      "League Title",
      "UEFA Cup"
    ]
  },
  {
    "season": "1973\u201374",
    "division": "Division 1",
    "played": 42,
    "won": 22,
    "drawn": 13,
    "lost": 7,
    "gf": 52,
    "ga": 31,
    "pts": 57,
    "pos": 2,
    "faCup": "W",
    "leagueCup": "R5",
    "commShield": "\u2014",
    "championsLeague": "R2",
    "europaLeague": "\u2014",
    "superCup": "\u2014",
    "clubWorldCup": "\u2014",
    "topScorer": "Kevin Keegan",
    "topScorerGoals": 19,
    "manager": "Bill Shankly",
    "highlight": "Silverware won: FA Cup. Finished 2nd in the Division 1 under manager Bill Shankly. Top scorer Kevin Keegan scored 19 goals.",
    "majorTrophies": [
      "FA Cup"
    ]
  },
  {
    "season": "1974\u201375",
    "division": "Division 1",
    "played": 42,
    "won": 20,
    "drawn": 11,
    "lost": 11,
    "gf": 60,
    "ga": 39,
    "pts": 51,
    "pos": 2,
    "faCup": "R4",
    "leagueCup": "R4",
    "commShield": "W",
    "championsLeague": "\u2014",
    "europaLeague": "\u2014",
    "superCup": "\u2014",
    "clubWorldCup": "\u2014",
    "topScorer": "Steve Heighway",
    "topScorerGoals": 13,
    "manager": "Bob Paisley",
    "highlight": "Silverware won: Community Shield. Finished 2nd in the Division 1 under manager Bob Paisley. Top scorer Steve Heighway scored 13 goals.",
    "majorTrophies": [
      "Community Shield"
    ]
  },
  {
    "season": "1975\u201376",
    "division": "Division 1",
    "played": 42,
    "won": 23,
    "drawn": 14,
    "lost": 5,
    "gf": 66,
    "ga": 31,
    "pts": 60,
    "pos": 1,
    "faCup": "R4",
    "leagueCup": "R3",
    "commShield": "\u2014",
    "championsLeague": "\u2014",
    "europaLeague": "W",
    "superCup": "\u2014",
    "clubWorldCup": "\u2014",
    "topScorer": "John Toshack",
    "topScorerGoals": 23,
    "manager": "Bob Paisley",
    "highlight": "Silverware won: League Title, UEFA Cup. Finished 1st in the Division 1 under manager Bob Paisley. Top scorer John Toshack scored 23 goals.",
    "majorTrophies": [
      "League Title",
      "UEFA Cup"
    ]
  },
  {
    "season": "1976\u201377",
    "division": "Division 1",
    "played": 42,
    "won": 23,
    "drawn": 11,
    "lost": 8,
    "gf": 62,
    "ga": 33,
    "pts": 57,
    "pos": 1,
    "faCup": "RU",
    "leagueCup": "R2",
    "commShield": "W",
    "championsLeague": "W",
    "europaLeague": "\u2014",
    "superCup": "\u2014",
    "clubWorldCup": "\u2014",
    "topScorer": "Kevin Keegan",
    "topScorerGoals": 20,
    "manager": "Bob Paisley",
    "highlight": "Silverware won: League Title, Community Shield, Champions League. Bob Paisley's legendary team won the First Division title and captured Liverpool's first-ever European Cup (Champions League) in Rome, defeating M\u00f6nchengladbach 3-1.",
    "majorTrophies": [
      "League Title",
      "Community Shield",
      "Champions League"
    ]
  },
  {
    "season": "1977\u201378",
    "division": "Division 1",
    "played": 42,
    "won": 24,
    "drawn": 9,
    "lost": 9,
    "gf": 65,
    "ga": 34,
    "pts": 57,
    "pos": 2,
    "faCup": "R3",
    "leagueCup": "RU",
    "commShield": "W[h]",
    "championsLeague": "W",
    "europaLeague": "\u2014",
    "superCup": "W",
    "clubWorldCup": "\u2014",
    "topScorer": "Kenny Dalglish",
    "topScorerGoals": 31,
    "manager": "Bob Paisley",
    "highlight": "Silverware won: Community Shield, Champions League, UEFA Super Cup. Retained the European Cup! Kenny Dalglish scored the winning goal at Wembley against Club Brugge to secure Liverpool's second consecutive European title.",
    "majorTrophies": [
      "Community Shield",
      "Champions League",
      "UEFA Super Cup"
    ]
  },
  {
    "season": "1978\u201379",
    "division": "Division 1",
    "played": 42,
    "won": 30,
    "drawn": 8,
    "lost": 4,
    "gf": 85,
    "ga": 16,
    "pts": 68,
    "pos": 1,
    "faCup": "SF",
    "leagueCup": "R2",
    "commShield": "\u2014",
    "championsLeague": "R1",
    "europaLeague": "\u2014",
    "superCup": "RU",
    "clubWorldCup": "\u2014",
    "topScorer": "Kenny Dalglish",
    "topScorerGoals": 25,
    "manager": "Bob Paisley",
    "highlight": "Silverware won: League Title. Finished 1st in the Division 1 under manager Bob Paisley. Top scorer Kenny Dalglish scored 25 goals.",
    "majorTrophies": [
      "League Title"
    ]
  },
  {
    "season": "1979\u201380",
    "division": "Division 1",
    "played": 42,
    "won": 25,
    "drawn": 10,
    "lost": 7,
    "gf": 81,
    "ga": 30,
    "pts": 60,
    "pos": 1,
    "faCup": "SF",
    "leagueCup": "SF",
    "commShield": "W",
    "championsLeague": "R1",
    "europaLeague": "\u2014",
    "superCup": "\u2014",
    "clubWorldCup": "\u2014",
    "topScorer": "David Johnson",
    "topScorerGoals": 27,
    "manager": "Bob Paisley",
    "highlight": "Silverware won: League Title, Community Shield. Finished 1st in the Division 1 under manager Bob Paisley. Top scorer David Johnson scored 27 goals.",
    "majorTrophies": [
      "League Title",
      "Community Shield"
    ]
  },
  {
    "season": "1980\u201381",
    "division": "Division 1",
    "played": 42,
    "won": 17,
    "drawn": 17,
    "lost": 8,
    "gf": 62,
    "ga": 42,
    "pts": 51,
    "pos": 5,
    "faCup": "R4",
    "leagueCup": "W",
    "commShield": "W",
    "championsLeague": "W",
    "europaLeague": "\u2014",
    "superCup": "\u2014",
    "clubWorldCup": "\u2014",
    "topScorer": "Terry Mc, Dermott",
    "topScorerGoals": 22,
    "manager": "Bob Paisley",
    "highlight": "Silverware won: League Cup, Community Shield, Champions League. Finished 5th in the Division 1 under manager Bob Paisley. Top scorer Terry Mc, Dermott scored 22 goals.",
    "majorTrophies": [
      "League Cup",
      "Community Shield",
      "Champions League"
    ]
  },
  {
    "season": "1981\u201382",
    "division": "Division 1",
    "played": 42,
    "won": 26,
    "drawn": 9,
    "lost": 7,
    "gf": 80,
    "ga": 32,
    "pts": 87,
    "pos": 1,
    "faCup": "R5",
    "leagueCup": "W",
    "commShield": "\u2014",
    "championsLeague": "QF",
    "europaLeague": "\u2014",
    "superCup": "\u2014",
    "clubWorldCup": "RU",
    "topScorer": "Ian Rush",
    "topScorerGoals": 30,
    "manager": "Bob Paisley",
    "highlight": "Silverware won: League Title, League Cup. Finished 1st in the Division 1 under manager Bob Paisley. Top scorer Ian Rush scored 30 goals.",
    "majorTrophies": [
      "League Title",
      "League Cup"
    ]
  },
  {
    "season": "1982\u201383",
    "division": "Division 1",
    "played": 42,
    "won": 24,
    "drawn": 10,
    "lost": 8,
    "gf": 87,
    "ga": 37,
    "pts": 82,
    "pos": 1,
    "faCup": "R5",
    "leagueCup": "W",
    "commShield": "W",
    "championsLeague": "QF",
    "europaLeague": "\u2014",
    "superCup": "\u2014",
    "clubWorldCup": "\u2014",
    "topScorer": "Ian Rush",
    "topScorerGoals": 31,
    "manager": "Bob Paisley",
    "highlight": "Silverware won: League Title, League Cup, Community Shield. Finished 1st in the Division 1 under manager Bob Paisley. Top scorer Ian Rush scored 31 goals.",
    "majorTrophies": [
      "League Title",
      "League Cup",
      "Community Shield"
    ]
  },
  {
    "season": "1983\u201384",
    "division": "Division 1",
    "played": 42,
    "won": 22,
    "drawn": 14,
    "lost": 6,
    "gf": 73,
    "ga": 32,
    "pts": 80,
    "pos": 1,
    "faCup": "R4",
    "leagueCup": "W",
    "commShield": "RU",
    "championsLeague": "W",
    "europaLeague": "\u2014",
    "superCup": "\u2014",
    "clubWorldCup": "\u2014",
    "topScorer": "Ian Rush",
    "topScorerGoals": 47,
    "manager": "Joe Fagan",
    "highlight": "Silverware won: League Title, League Cup, Champions League. An unprecedented treble! Under Joe Fagan, Liverpool won the League Title, the European Cup (defeating Roma in Roma), and the League Cup.",
    "majorTrophies": [
      "League Title",
      "League Cup",
      "Champions League"
    ]
  },
  {
    "season": "1984\u201385",
    "division": "Division 1",
    "played": 42,
    "won": 22,
    "drawn": 11,
    "lost": 9,
    "gf": 68,
    "ga": 35,
    "pts": 77,
    "pos": 2,
    "faCup": "SF",
    "leagueCup": "R3",
    "commShield": "RU",
    "championsLeague": "RU",
    "europaLeague": "\u2014",
    "superCup": "RU",
    "clubWorldCup": "RU",
    "topScorer": "John Wark",
    "topScorerGoals": 27,
    "manager": "Joe Fagan",
    "highlight": "Finished 2nd in the Division 1 under manager Joe Fagan. Top scorer John Wark scored 27 goals.",
    "majorTrophies": []
  },
  {
    "season": "1985\u201386",
    "division": "Division 1",
    "played": 42,
    "won": 26,
    "drawn": 10,
    "lost": 6,
    "gf": 89,
    "ga": 37,
    "pts": 88,
    "pos": 1,
    "faCup": "W",
    "leagueCup": "SF",
    "commShield": "\u2014",
    "championsLeague": "\u2014",
    "europaLeague": "\u2014",
    "superCup": "\u2014",
    "clubWorldCup": "\u2014",
    "topScorer": "Ian Rush",
    "topScorerGoals": 33,
    "manager": "Kenny Dalglish",
    "highlight": "Silverware won: League Title, FA Cup. The Double! In Kenny Dalglish's first season as player-manager, Liverpool won both the First Division League Title and the FA Cup, beating rivals Everton.",
    "majorTrophies": [
      "League Title",
      "FA Cup"
    ]
  },
  {
    "season": "1986\u201387",
    "division": "Division 1",
    "played": 42,
    "won": 23,
    "drawn": 8,
    "lost": 11,
    "gf": 72,
    "ga": 42,
    "pts": 77,
    "pos": 2,
    "faCup": "R3",
    "leagueCup": "RU",
    "commShield": "W[h]",
    "championsLeague": "\u2014",
    "europaLeague": "\u2014",
    "superCup": "\u2014",
    "clubWorldCup": "\u2014",
    "topScorer": "Ian Rush",
    "topScorerGoals": 40,
    "manager": "Kenny Dalglish",
    "highlight": "Silverware won: Community Shield. Finished 2nd in the Division 1 under manager Kenny Dalglish. Top scorer Ian Rush scored 40 goals.",
    "majorTrophies": [
      "Community Shield"
    ]
  },
  {
    "season": "1987\u201388",
    "division": "Division 1",
    "played": 40,
    "won": 26,
    "drawn": 12,
    "lost": 2,
    "gf": 87,
    "ga": 24,
    "pts": 90,
    "pos": 1,
    "faCup": "RU",
    "leagueCup": "R3",
    "commShield": "\u2014",
    "championsLeague": "\u2014",
    "europaLeague": "\u2014",
    "superCup": "\u2014",
    "clubWorldCup": "\u2014",
    "topScorer": "John Aldridge",
    "topScorerGoals": 29,
    "manager": "Kenny Dalglish",
    "highlight": "Silverware won: League Title. Finished 1st in the Division 1 under manager Kenny Dalglish. Top scorer John Aldridge scored 29 goals.",
    "majorTrophies": [
      "League Title"
    ]
  },
  {
    "season": "1988\u201389",
    "division": "Division 1",
    "played": 38,
    "won": 22,
    "drawn": 10,
    "lost": 6,
    "gf": 65,
    "ga": 28,
    "pts": 76,
    "pos": 2,
    "faCup": "W",
    "leagueCup": "R4",
    "commShield": "W",
    "championsLeague": "\u2014",
    "europaLeague": "\u2014",
    "superCup": "\u2014",
    "clubWorldCup": "\u2014",
    "topScorer": "John Aldridge",
    "topScorerGoals": 31,
    "manager": "Kenny Dalglish",
    "highlight": "Silverware won: FA Cup, Community Shield. Finished 2nd in the Division 1 under manager Kenny Dalglish. Top scorer John Aldridge scored 31 goals.",
    "majorTrophies": [
      "FA Cup",
      "Community Shield"
    ]
  },
  {
    "season": "1989\u201390",
    "division": "Division 1",
    "played": 38,
    "won": 23,
    "drawn": 10,
    "lost": 5,
    "gf": 78,
    "ga": 37,
    "pts": 79,
    "pos": 1,
    "faCup": "SF",
    "leagueCup": "R3",
    "commShield": "W",
    "championsLeague": "\u2014",
    "europaLeague": "\u2014",
    "superCup": "\u2014",
    "clubWorldCup": "\u2014",
    "topScorer": "John Barnes",
    "topScorerGoals": 28,
    "manager": "Kenny Dalglish",
    "highlight": "Silverware won: League Title, Community Shield. Liverpool won their 18th top-flight league title under Dalglish, which would stand as their last league championship for 30 years.",
    "majorTrophies": [
      "League Title",
      "Community Shield"
    ]
  },
  {
    "season": "1990\u201391",
    "division": "Division 1",
    "played": 38,
    "won": 23,
    "drawn": 7,
    "lost": 8,
    "gf": 77,
    "ga": 40,
    "pts": 76,
    "pos": 2,
    "faCup": "R5",
    "leagueCup": "R3",
    "commShield": "W[h]",
    "championsLeague": "\u2014",
    "europaLeague": "\u2014",
    "superCup": "\u2014",
    "clubWorldCup": "\u2014",
    "topScorer": "Ian Rush",
    "topScorerGoals": 26,
    "manager": "Kenny Dalglish / Graeme Souness",
    "highlight": "Silverware won: Community Shield. Finished 2nd in the Division 1 under manager Kenny Dalglish / Graeme Souness. Top scorer Ian Rush scored 26 goals.",
    "majorTrophies": [
      "Community Shield"
    ]
  },
  {
    "season": "1991\u201392",
    "division": "Division 1",
    "played": 42,
    "won": 16,
    "drawn": 16,
    "lost": 10,
    "gf": 47,
    "ga": 40,
    "pts": 64,
    "pos": 6,
    "faCup": "W",
    "leagueCup": "R4",
    "commShield": "\u2014",
    "championsLeague": "\u2014",
    "europaLeague": "QF",
    "superCup": "\u2014",
    "clubWorldCup": "\u2014",
    "topScorer": "Dean Saunders",
    "topScorerGoals": 23,
    "manager": "Graeme Souness",
    "highlight": "Silverware won: FA Cup. Finished 6th in the Division 1 under manager Graeme Souness. Top scorer Dean Saunders scored 23 goals.",
    "majorTrophies": [
      "FA Cup"
    ]
  },
  {
    "season": "1992\u201393",
    "division": "PL",
    "played": 42,
    "won": 16,
    "drawn": 11,
    "lost": 15,
    "gf": 62,
    "ga": 55,
    "pts": 59,
    "pos": 6,
    "faCup": "R3",
    "leagueCup": "R4",
    "commShield": "RU",
    "championsLeague": "\u2014",
    "europaLeague": "\u2014",
    "superCup": "\u2014",
    "clubWorldCup": "\u2014",
    "topScorer": "Ian Rush",
    "topScorerGoals": 22,
    "manager": "Graeme Souness",
    "highlight": "Finished 6th in the Premier League under manager Graeme Souness. Top scorer Ian Rush scored 22 goals.",
    "majorTrophies": []
  },
  {
    "season": "1993\u201394",
    "division": "PL",
    "played": 42,
    "won": 17,
    "drawn": 9,
    "lost": 16,
    "gf": 59,
    "ga": 55,
    "pts": 60,
    "pos": 8,
    "faCup": "R3",
    "leagueCup": "R4",
    "commShield": "\u2014",
    "championsLeague": "\u2014",
    "europaLeague": "\u2014",
    "superCup": "\u2014",
    "clubWorldCup": "\u2014",
    "topScorer": "Ian Rush",
    "topScorerGoals": 19,
    "manager": "Graeme Souness / Roy Evans",
    "highlight": "Finished 8th in the Premier League under manager Graeme Souness / Roy Evans. Top scorer Ian Rush scored 19 goals.",
    "majorTrophies": []
  },
  {
    "season": "1994\u201395",
    "division": "PL",
    "played": 42,
    "won": 21,
    "drawn": 11,
    "lost": 10,
    "gf": 65,
    "ga": 37,
    "pts": 74,
    "pos": 4,
    "faCup": "R6",
    "leagueCup": "W",
    "commShield": "\u2014",
    "championsLeague": "\u2014",
    "europaLeague": "\u2014",
    "superCup": "\u2014",
    "clubWorldCup": "\u2014",
    "topScorer": "Robbie Fowler",
    "topScorerGoals": 31,
    "manager": "Roy Evans",
    "highlight": "Silverware won: League Cup. Finished 4th in the Premier League under manager Roy Evans. Top scorer Robbie Fowler scored 31 goals.",
    "majorTrophies": [
      "League Cup"
    ]
  },
  {
    "season": "1995\u201396",
    "division": "PL",
    "played": 38,
    "won": 20,
    "drawn": 11,
    "lost": 7,
    "gf": 70,
    "ga": 34,
    "pts": 71,
    "pos": 3,
    "faCup": "RU",
    "leagueCup": "R4",
    "commShield": "\u2014",
    "championsLeague": "\u2014",
    "europaLeague": "R2",
    "superCup": "\u2014",
    "clubWorldCup": "\u2014",
    "topScorer": "Robbie Fowler",
    "topScorerGoals": 36,
    "manager": "Roy Evans",
    "highlight": "Finished 3rd in the Premier League under manager Roy Evans. Top scorer Robbie Fowler scored 36 goals.",
    "majorTrophies": []
  },
  {
    "season": "1996\u201397",
    "division": "PL",
    "played": 38,
    "won": 19,
    "drawn": 11,
    "lost": 8,
    "gf": 62,
    "ga": 37,
    "pts": 68,
    "pos": 4,
    "faCup": "R4",
    "leagueCup": "R5",
    "commShield": "\u2014",
    "championsLeague": "\u2014",
    "europaLeague": "\u2014",
    "superCup": "\u2014",
    "clubWorldCup": "\u2014",
    "topScorer": "Robbie Fowler",
    "topScorerGoals": 31,
    "manager": "Roy Evans",
    "highlight": "Finished 4th in the Premier League under manager Roy Evans. Top scorer Robbie Fowler scored 31 goals.",
    "majorTrophies": []
  },
  {
    "season": "1997\u201398",
    "division": "PL",
    "played": 38,
    "won": 18,
    "drawn": 11,
    "lost": 9,
    "gf": 68,
    "ga": 42,
    "pts": 65,
    "pos": 3,
    "faCup": "R3",
    "leagueCup": "SF",
    "commShield": "\u2014",
    "championsLeague": "\u2014",
    "europaLeague": "R2",
    "superCup": "\u2014",
    "clubWorldCup": "\u2014",
    "topScorer": "Michael Owen",
    "topScorerGoals": 23,
    "manager": "Roy Evans",
    "highlight": "Finished 3rd in the Premier League under manager Roy Evans. Top scorer Michael Owen scored 23 goals.",
    "majorTrophies": []
  },
  {
    "season": "1998\u201399",
    "division": "PL",
    "played": 38,
    "won": 15,
    "drawn": 9,
    "lost": 14,
    "gf": 68,
    "ga": 49,
    "pts": 54,
    "pos": 7,
    "faCup": "R4",
    "leagueCup": "R4",
    "commShield": "\u2014",
    "championsLeague": "\u2014",
    "europaLeague": "R3",
    "superCup": "\u2014",
    "clubWorldCup": "\u2014",
    "topScorer": "Michael Owen",
    "topScorerGoals": 23,
    "manager": "Roy Evans / G\u00e9rard Houllier",
    "highlight": "Finished 7th in the Premier League under manager Roy Evans / G\u00e9rard Houllier. Top scorer Michael Owen scored 23 goals.",
    "majorTrophies": []
  },
  {
    "season": "1999\u20132000",
    "division": "PL",
    "played": 38,
    "won": 19,
    "drawn": 10,
    "lost": 9,
    "gf": 51,
    "ga": 30,
    "pts": 67,
    "pos": 4,
    "faCup": "R4",
    "leagueCup": "R3",
    "commShield": "\u2014",
    "championsLeague": "\u2014",
    "europaLeague": "\u2014",
    "superCup": "\u2014",
    "clubWorldCup": "\u2014",
    "topScorer": "Michael Owen",
    "topScorerGoals": 12,
    "manager": "G\u00e9rard Houllier",
    "highlight": "Finished 4th in the Premier League under manager G\u00e9rard Houllier. Top scorer Michael Owen scored 12 goals.",
    "majorTrophies": []
  },
  {
    "season": "2000\u201301",
    "division": "PL",
    "played": 38,
    "won": 20,
    "drawn": 9,
    "lost": 9,
    "gf": 71,
    "ga": 39,
    "pts": 69,
    "pos": 3,
    "faCup": "W",
    "leagueCup": "W",
    "commShield": "\u2014",
    "championsLeague": "\u2014",
    "europaLeague": "W",
    "superCup": "\u2014",
    "clubWorldCup": "\u2014",
    "topScorer": "Michael Owen",
    "topScorerGoals": 24,
    "manager": "G\u00e9rard Houllier",
    "highlight": "Silverware won: FA Cup, League Cup, UEFA Cup. The famous Cup Treble under G\u00e9rard Houllier! Liverpool won the FA Cup, League Cup, and UEFA Cup in a dramatic and grueling 63-match season.",
    "majorTrophies": [
      "FA Cup",
      "League Cup",
      "UEFA Cup"
    ]
  },
  {
    "season": "2001\u201302",
    "division": "PL",
    "played": 38,
    "won": 24,
    "drawn": 8,
    "lost": 6,
    "gf": 67,
    "ga": 30,
    "pts": 80,
    "pos": 2,
    "faCup": "R4",
    "leagueCup": "R3",
    "commShield": "W",
    "championsLeague": "QF",
    "europaLeague": "\u2014",
    "superCup": "W",
    "clubWorldCup": "\u2014",
    "topScorer": "Michael Owen",
    "topScorerGoals": 29,
    "manager": "G\u00e9rard Houllier",
    "highlight": "Silverware won: Community Shield, UEFA Super Cup. Finished 2nd in the Premier League under manager G\u00e9rard Houllier. Top scorer Michael Owen scored 29 goals.",
    "majorTrophies": [
      "Community Shield",
      "UEFA Super Cup"
    ]
  },
  {
    "season": "2002\u201303",
    "division": "PL",
    "played": 38,
    "won": 18,
    "drawn": 10,
    "lost": 10,
    "gf": 61,
    "ga": 41,
    "pts": 64,
    "pos": 5,
    "faCup": "R4",
    "leagueCup": "W",
    "commShield": "RU",
    "championsLeague": "Grp[n]",
    "europaLeague": "QF",
    "superCup": "\u2014",
    "clubWorldCup": "\u2014",
    "topScorer": "Michael Owen",
    "topScorerGoals": 28,
    "manager": "G\u00e9rard Houllier",
    "highlight": "Silverware won: League Cup. Finished 5th in the Premier League under manager G\u00e9rard Houllier. Top scorer Michael Owen scored 28 goals.",
    "majorTrophies": [
      "League Cup"
    ]
  },
  {
    "season": "2003\u201304",
    "division": "PL",
    "played": 38,
    "won": 16,
    "drawn": 12,
    "lost": 10,
    "gf": 55,
    "ga": 37,
    "pts": 60,
    "pos": 4,
    "faCup": "R5",
    "leagueCup": "R4",
    "commShield": "\u2014",
    "championsLeague": "\u2014",
    "europaLeague": "R4",
    "superCup": "\u2014",
    "clubWorldCup": "\u2014",
    "topScorer": "Michael Owen",
    "topScorerGoals": 19,
    "manager": "G\u00e9rard Houllier",
    "highlight": "Finished 4th in the Premier League under manager G\u00e9rard Houllier. Top scorer Michael Owen scored 19 goals.",
    "majorTrophies": []
  },
  {
    "season": "2004\u201305",
    "division": "PL",
    "played": 38,
    "won": 17,
    "drawn": 7,
    "lost": 14,
    "gf": 52,
    "ga": 41,
    "pts": 58,
    "pos": 5,
    "faCup": "R3",
    "leagueCup": "RU",
    "commShield": "\u2014",
    "championsLeague": "W",
    "europaLeague": "\u2014",
    "superCup": "\u2014",
    "clubWorldCup": "\u2014",
    "topScorer": "Milan Baro\u0161, Luis Garc\u00eda, Steven Gerrard",
    "topScorerGoals": 13,
    "manager": "Rafael Ben\u00edtez",
    "highlight": "Silverware won: Champions League. The Miracle of Istanbul! Trailing AC Milan 3-0 at half-time, Rafa Ben\u00edtez's side drew 3-3 and won on penalties, capturing their 5th Champions League.",
    "majorTrophies": [
      "Champions League"
    ]
  },
  {
    "season": "2005\u201306",
    "division": "PL",
    "played": 38,
    "won": 25,
    "drawn": 7,
    "lost": 6,
    "gf": 57,
    "ga": 25,
    "pts": 82,
    "pos": 3,
    "faCup": "W",
    "leagueCup": "R3",
    "commShield": "\u2014",
    "championsLeague": "R16",
    "europaLeague": "\u2014",
    "superCup": "W",
    "clubWorldCup": "RU",
    "topScorer": "Steven Gerrard",
    "topScorerGoals": 23,
    "manager": "Rafael Ben\u00edtez",
    "highlight": "Silverware won: FA Cup, UEFA Super Cup. Finished 3rd in the Premier League under manager Rafael Ben\u00edtez. Top scorer Steven Gerrard scored 23 goals.",
    "majorTrophies": [
      "FA Cup",
      "UEFA Super Cup"
    ]
  },
  {
    "season": "2006\u201307",
    "division": "PL",
    "played": 38,
    "won": 20,
    "drawn": 8,
    "lost": 10,
    "gf": 57,
    "ga": 27,
    "pts": 68,
    "pos": 3,
    "faCup": "R3",
    "leagueCup": "R5",
    "commShield": "W",
    "championsLeague": "RU",
    "europaLeague": "\u2014",
    "superCup": "\u2014",
    "clubWorldCup": "\u2014",
    "topScorer": "Peter Crouch",
    "topScorerGoals": 18,
    "manager": "Rafael Ben\u00edtez",
    "highlight": "Silverware won: Community Shield. Finished 3rd in the Premier League under manager Rafael Ben\u00edtez. Top scorer Peter Crouch scored 18 goals.",
    "majorTrophies": [
      "Community Shield"
    ]
  },
  {
    "season": "2007\u201308",
    "division": "PL",
    "played": 38,
    "won": 21,
    "drawn": 13,
    "lost": 4,
    "gf": 67,
    "ga": 28,
    "pts": 76,
    "pos": 4,
    "faCup": "R5",
    "leagueCup": "R5",
    "commShield": "\u2014",
    "championsLeague": "SF",
    "europaLeague": "\u2014",
    "superCup": "\u2014",
    "clubWorldCup": "\u2014",
    "topScorer": "Fernando Torres",
    "topScorerGoals": 33,
    "manager": "Rafael Ben\u00edtez",
    "highlight": "Finished 4th in the Premier League under manager Rafael Ben\u00edtez. Top scorer Fernando Torres scored 33 goals.",
    "majorTrophies": []
  },
  {
    "season": "2008\u201309",
    "division": "PL",
    "played": 38,
    "won": 25,
    "drawn": 11,
    "lost": 2,
    "gf": 77,
    "ga": 27,
    "pts": 86,
    "pos": 2,
    "faCup": "R4",
    "leagueCup": "R4",
    "commShield": "\u2014",
    "championsLeague": "QF",
    "europaLeague": "\u2014",
    "superCup": "\u2014",
    "clubWorldCup": "\u2014",
    "topScorer": "Steven Gerrard",
    "topScorerGoals": 24,
    "manager": "Rafael Ben\u00edtez",
    "highlight": "Finished 2nd in the Premier League under manager Rafael Ben\u00edtez. Top scorer Steven Gerrard scored 24 goals.",
    "majorTrophies": []
  },
  {
    "season": "2009\u201310",
    "division": "PL",
    "played": 38,
    "won": 18,
    "drawn": 9,
    "lost": 11,
    "gf": 61,
    "ga": 35,
    "pts": 63,
    "pos": 7,
    "faCup": "R3",
    "leagueCup": "R4",
    "commShield": "\u2014",
    "championsLeague": "Grp[n]",
    "europaLeague": "SF",
    "superCup": "\u2014",
    "clubWorldCup": "\u2014",
    "topScorer": "Fernando Torres",
    "topScorerGoals": 22,
    "manager": "Rafael Ben\u00edtez",
    "highlight": "Finished 7th in the Premier League under manager Rafael Ben\u00edtez. Top scorer Fernando Torres scored 22 goals.",
    "majorTrophies": []
  },
  {
    "season": "2010\u201311",
    "division": "PL",
    "played": 38,
    "won": 17,
    "drawn": 7,
    "lost": 14,
    "gf": 59,
    "ga": 44,
    "pts": 58,
    "pos": 6,
    "faCup": "R3",
    "leagueCup": "R3",
    "commShield": "\u2014",
    "championsLeague": "\u2014",
    "europaLeague": "R16",
    "superCup": "\u2014",
    "clubWorldCup": "\u2014",
    "topScorer": "Dirk Kuyt",
    "topScorerGoals": 15,
    "manager": "Roy Hodgson / Kenny Dalglish",
    "highlight": "Finished 6th in the Premier League under manager Roy Hodgson / Kenny Dalglish. Top scorer Dirk Kuyt scored 15 goals.",
    "majorTrophies": []
  },
  {
    "season": "2011\u201312",
    "division": "PL",
    "played": 38,
    "won": 14,
    "drawn": 10,
    "lost": 14,
    "gf": 47,
    "ga": 40,
    "pts": 52,
    "pos": 8,
    "faCup": "RU",
    "leagueCup": "W",
    "commShield": "\u2014",
    "championsLeague": "\u2014",
    "europaLeague": "\u2014",
    "superCup": "\u2014",
    "clubWorldCup": "\u2014",
    "topScorer": "Luis Su\u00e1rez",
    "topScorerGoals": 17,
    "manager": "Kenny Dalglish",
    "highlight": "Silverware won: League Cup. Finished 8th in the Premier League under manager Kenny Dalglish. Top scorer Luis Su\u00e1rez scored 17 goals.",
    "majorTrophies": [
      "League Cup"
    ]
  },
  {
    "season": "2012\u201313",
    "division": "PL",
    "played": 38,
    "won": 16,
    "drawn": 13,
    "lost": 9,
    "gf": 71,
    "ga": 43,
    "pts": 61,
    "pos": 7,
    "faCup": "R4",
    "leagueCup": "R4",
    "commShield": "\u2014",
    "championsLeague": "\u2014",
    "europaLeague": "R32",
    "superCup": "\u2014",
    "clubWorldCup": "\u2014",
    "topScorer": "Luis Su\u00e1rez",
    "topScorerGoals": 30,
    "manager": "Brendan Rodgers",
    "highlight": "Finished 7th in the Premier League under manager Brendan Rodgers. Top scorer Luis Su\u00e1rez scored 30 goals.",
    "majorTrophies": []
  },
  {
    "season": "2013\u201314",
    "division": "PL",
    "played": 38,
    "won": 26,
    "drawn": 6,
    "lost": 6,
    "gf": 101,
    "ga": 50,
    "pts": 84,
    "pos": 2,
    "faCup": "R5",
    "leagueCup": "R3",
    "commShield": "\u2014",
    "championsLeague": "\u2014",
    "europaLeague": "\u2014",
    "superCup": "\u2014",
    "clubWorldCup": "\u2014",
    "topScorer": "Luis Su\u00e1rez",
    "topScorerGoals": 31,
    "manager": "Brendan Rodgers",
    "highlight": "Finished 2nd in the Premier League under manager Brendan Rodgers. Top scorer Luis Su\u00e1rez scored 31 goals.",
    "majorTrophies": []
  },
  {
    "season": "2014\u201315",
    "division": "PL",
    "played": 38,
    "won": 18,
    "drawn": 8,
    "lost": 12,
    "gf": 52,
    "ga": 48,
    "pts": 62,
    "pos": 6,
    "faCup": "SF",
    "leagueCup": "SF",
    "commShield": "\u2014",
    "championsLeague": "Grp[n]",
    "europaLeague": "R32",
    "superCup": "\u2014",
    "clubWorldCup": "\u2014",
    "topScorer": "Steven Gerrard",
    "topScorerGoals": 13,
    "manager": "Brendan Rodgers",
    "highlight": "Finished 6th in the Premier League under manager Brendan Rodgers. Top scorer Steven Gerrard scored 13 goals.",
    "majorTrophies": []
  },
  {
    "season": "2015\u201316",
    "division": "PL",
    "played": 38,
    "won": 16,
    "drawn": 12,
    "lost": 10,
    "gf": 63,
    "ga": 50,
    "pts": 60,
    "pos": 8,
    "faCup": "R4",
    "leagueCup": "RU",
    "commShield": "\u2014",
    "championsLeague": "\u2014",
    "europaLeague": "RU",
    "superCup": "\u2014",
    "clubWorldCup": "\u2014",
    "topScorer": "Daniel Sturridge",
    "topScorerGoals": 13,
    "manager": "Brendan Rodgers / J\u00fcrgen Klopp",
    "highlight": "Finished 8th in the Premier League under manager Brendan Rodgers / J\u00fcrgen Klopp. Top scorer Daniel Sturridge scored 13 goals.",
    "majorTrophies": []
  },
  {
    "season": "2016\u201317",
    "division": "PL",
    "played": 38,
    "won": 22,
    "drawn": 10,
    "lost": 6,
    "gf": 78,
    "ga": 42,
    "pts": 76,
    "pos": 4,
    "faCup": "R4",
    "leagueCup": "SF",
    "commShield": "\u2014",
    "championsLeague": "\u2014",
    "europaLeague": "\u2014",
    "superCup": "\u2014",
    "clubWorldCup": "\u2014",
    "topScorer": "Philippe Coutinho",
    "topScorerGoals": 14,
    "manager": "J\u00fcrgen Klopp",
    "highlight": "Finished 4th in the Premier League under manager J\u00fcrgen Klopp. Top scorer Philippe Coutinho scored 14 goals.",
    "majorTrophies": []
  },
  {
    "season": "2017\u201318",
    "division": "PL",
    "played": 38,
    "won": 21,
    "drawn": 12,
    "lost": 5,
    "gf": 84,
    "ga": 38,
    "pts": 75,
    "pos": 4,
    "faCup": "R4",
    "leagueCup": "R3",
    "commShield": "\u2014",
    "championsLeague": "RU",
    "europaLeague": "\u2014",
    "superCup": "\u2014",
    "clubWorldCup": "\u2014",
    "topScorer": "Mohamed Salah",
    "topScorerGoals": 44,
    "manager": "J\u00fcrgen Klopp",
    "highlight": "Finished 4th in the Premier League under manager J\u00fcrgen Klopp. Top scorer Mohamed Salah scored 44 goals.",
    "majorTrophies": []
  },
  {
    "season": "2018\u201319",
    "division": "PL",
    "played": 38,
    "won": 30,
    "drawn": 7,
    "lost": 1,
    "gf": 89,
    "ga": 22,
    "pts": 97,
    "pos": 2,
    "faCup": "R3",
    "leagueCup": "R3",
    "commShield": "\u2014",
    "championsLeague": "W",
    "europaLeague": "\u2014",
    "superCup": "\u2014",
    "clubWorldCup": "\u2014",
    "topScorer": "Mohamed Salah",
    "topScorerGoals": 27,
    "manager": "J\u00fcrgen Klopp",
    "highlight": "Silverware won: Champions League. European Champions! Beat Tottenham 2-0 in Madrid to lift their 6th Champions League, after staging a legendary 4-0 semi-final comeback vs Barcelona.",
    "majorTrophies": [
      "Champions League"
    ]
  },
  {
    "season": "2019\u201320",
    "division": "PL",
    "played": 38,
    "won": 32,
    "drawn": 3,
    "lost": 3,
    "gf": 85,
    "ga": 33,
    "pts": 99,
    "pos": 1,
    "faCup": "R5",
    "leagueCup": "QF",
    "commShield": "RU",
    "championsLeague": "R16",
    "europaLeague": "\u2014",
    "superCup": "W",
    "clubWorldCup": "W",
    "topScorer": "Mohamed Salah",
    "topScorerGoals": 23,
    "manager": "J\u00fcrgen Klopp",
    "highlight": "Silverware won: League Title, UEFA Super Cup, Club World Cup. The 30-Year Wait Ends! J\u00fcrgen Klopp's relentless side secured the Premier League title in record time, finishing on 99 points.",
    "majorTrophies": [
      "League Title",
      "UEFA Super Cup",
      "Club World Cup"
    ]
  },
  {
    "season": "2020\u201321",
    "division": "PL",
    "played": 38,
    "won": 20,
    "drawn": 9,
    "lost": 9,
    "gf": 68,
    "ga": 42,
    "pts": 69,
    "pos": 3,
    "faCup": "R4",
    "leagueCup": "R4",
    "commShield": "RU",
    "championsLeague": "QF",
    "europaLeague": "\u2014",
    "superCup": "\u2014",
    "clubWorldCup": "\u2014",
    "topScorer": "Mohamed Salah",
    "topScorerGoals": 31,
    "manager": "J\u00fcrgen Klopp",
    "highlight": "Finished 3rd in the Premier League under manager J\u00fcrgen Klopp. Top scorer Mohamed Salah scored 31 goals.",
    "majorTrophies": []
  },
  {
    "season": "2021\u201322",
    "division": "PL",
    "played": 38,
    "won": 28,
    "drawn": 8,
    "lost": 2,
    "gf": 94,
    "ga": 26,
    "pts": 92,
    "pos": 2,
    "faCup": "W",
    "leagueCup": "W",
    "commShield": "\u2014",
    "championsLeague": "RU",
    "europaLeague": "\u2014",
    "superCup": "\u2014",
    "clubWorldCup": "\u2014",
    "topScorer": "Mohamed Salah",
    "topScorerGoals": 31,
    "manager": "J\u00fcrgen Klopp",
    "highlight": "Silverware won: FA Cup, League Cup. Finished 2nd in the Premier League under manager J\u00fcrgen Klopp. Top scorer Mohamed Salah scored 31 goals.",
    "majorTrophies": [
      "FA Cup",
      "League Cup"
    ]
  },
  {
    "season": "2022\u201323",
    "division": "PL",
    "played": 38,
    "won": 19,
    "drawn": 10,
    "lost": 9,
    "gf": 75,
    "ga": 47,
    "pts": 67,
    "pos": 5,
    "faCup": "R4",
    "leagueCup": "R4",
    "commShield": "W",
    "championsLeague": "R16",
    "europaLeague": "\u2014",
    "superCup": "\u2014",
    "clubWorldCup": "\u2014",
    "topScorer": "Mohamed Salah",
    "topScorerGoals": 30,
    "manager": "J\u00fcrgen Klopp",
    "highlight": "Silverware won: Community Shield. Finished 5th in the Premier League under manager J\u00fcrgen Klopp. Top scorer Mohamed Salah scored 30 goals.",
    "majorTrophies": [
      "Community Shield"
    ]
  },
  {
    "season": "2023\u201324",
    "division": "PL",
    "played": 38,
    "won": 24,
    "drawn": 10,
    "lost": 4,
    "gf": 86,
    "ga": 41,
    "pts": 82,
    "pos": 3,
    "faCup": "QF",
    "leagueCup": "W",
    "commShield": "\u2014",
    "championsLeague": "\u2014",
    "europaLeague": "QF",
    "superCup": "\u2014",
    "clubWorldCup": "\u2014",
    "topScorer": "Mohamed Salah",
    "topScorerGoals": 25,
    "manager": "J\u00fcrgen Klopp",
    "highlight": "Silverware won: League Cup. Finished 3rd in the Premier League under manager J\u00fcrgen Klopp. Top scorer Mohamed Salah scored 25 goals.",
    "majorTrophies": [
      "League Cup"
    ]
  },
  {
    "season": "2024\u201325",
    "division": "PL",
    "played": 38,
    "won": 25,
    "drawn": 9,
    "lost": 4,
    "gf": 86,
    "ga": 41,
    "pts": 84,
    "pos": 1,
    "faCup": "R4",
    "leagueCup": "RU",
    "commShield": "\u2014",
    "championsLeague": "R16",
    "europaLeague": "\u2014",
    "superCup": "\u2014",
    "clubWorldCup": "\u2014",
    "topScorer": "Mohamed Salah",
    "topScorerGoals": 34,
    "manager": "Arne Slot",
    "highlight": "Silverware won: League Title. Arne Slot's debut season ended in glory! Liverpool won the Premier League title, clinching the trophy with four games to spare and scoring 86 goals.",
    "majorTrophies": [
      "League Title"
    ]
  },
  {
    "season": "2025\u201326",
    "division": "PL",
    "played": 38,
    "won": 17,
    "drawn": 9,
    "lost": 12,
    "gf": 63,
    "ga": 53,
    "pts": 60,
    "pos": 5,
    "faCup": "QF",
    "leagueCup": "R4",
    "commShield": "RU",
    "championsLeague": "QF",
    "europaLeague": "\u2014",
    "superCup": "\u2014",
    "clubWorldCup": "\u2014",
    "topScorer": "Hugo Ekitike",
    "topScorerGoals": 17,
    "manager": "Arne Slot",
    "highlight": "Finished 5th in the Premier League under manager Arne Slot. Top scorer Hugo Ekitike scored 17 goals.",
    "majorTrophies": []
  }
];

const managersData = [
  {
    "name": "W. E. Barclay / John McKenna",
    "years": "1892\u20131896",
    "seasons": 4,
    "trophies": 3,
    "avgPosition": 1.0,
    "winRate": "68.2%",
    "trophiesList": [
      "Lancashire League Title (1893)",
      "Second Division Title (1894, 1896)"
    ],
    "description": "The foundation managers who oversaw Liverpool's entry into the football league, securing immediate promotion and Lancashire league honors."
  },
  {
    "name": "Tom Watson",
    "years": "1896\u20131915",
    "seasons": 19,
    "trophies": 3,
    "avgPosition": 6.8,
    "winRate": "46.1%",
    "trophiesList": [
      "First Division Title (1901, 1906)",
      "Second Division Title (1905)"
    ],
    "description": "Liverpool's first long-serving giant who won the club's first two top-flight English League championships."
  },
  {
    "name": "David Ashworth",
    "years": "1919\u20131923",
    "seasons": 3.5,
    "trophies": 1,
    "avgPosition": 2.5,
    "winRate": "51.8%",
    "trophiesList": [
      "First Division Title (1922)"
    ],
    "description": "Led the club to the post-WWI league championship in 1921-22 before leaving mid-way through the next title-winning season."
  },
  {
    "name": "Matt McQueen",
    "years": "1923\u20131928",
    "seasons": 5.5,
    "trophies": 1,
    "avgPosition": 8.0,
    "winRate": "40.9%",
    "trophiesList": [
      "First Division Title (1923)"
    ],
    "description": "Stepped in to secure the back-to-back league title in 1923 and oversaw the club throughout the mid-1920s."
  },
  {
    "name": "George Patterson",
    "years": "1928\u20131936",
    "seasons": 8,
    "trophies": 0,
    "avgPosition": 11.2,
    "winRate": "37.5%",
    "trophiesList": [],
    "description": "Served as both secretary and manager during a transitional era of consolidation in the top tier."
  },
  {
    "name": "George Kay",
    "years": "1936\u20131951",
    "seasons": 9,
    "trophies": 1,
    "avgPosition": 9.4,
    "winRate": "42.0%",
    "trophiesList": [
      "First Division Title (1947)"
    ],
    "description": "Guided Liverpool through WWII and won the historic post-war First Division Title in 1946-47."
  },
  {
    "name": "Don Welsh",
    "years": "1951\u20131956",
    "seasons": 5,
    "trophies": 0,
    "avgPosition": 15.0,
    "winRate": "38.6%",
    "trophiesList": [],
    "description": "Oversaw the squad during their relegation from Division 1 and early efforts to rebuild in Division 2."
  },
  {
    "name": "Phil Taylor",
    "years": "1956\u20131959",
    "seasons": 3,
    "trophies": 0,
    "avgPosition": 3.0,
    "winRate": "54.3%",
    "trophiesList": [],
    "description": "A former captain who narrowly missed promotion out of Division 2 before resigning in late 1959."
  },
  {
    "name": "Bill Shankly",
    "years": "1959\u20131974",
    "seasons": 15,
    "trophies": 11,
    "avgPosition": 3.4,
    "winRate": "51.9%",
    "trophiesList": [
      "First Division Title (1964, 1966, 1973)",
      "Second Division Title (1962)",
      "FA Cup (1965, 1974)",
      "UEFA Cup (1973)",
      "Community Shield (1964, 1965, 1966, 1974)"
    ],
    "description": "The father of modern Liverpool FC. Rebuilt the club from Second Division obscurity, established the famous 'Boot Room' culture, and laid the foundations of Anfield dominance."
  },
  {
    "name": "Bob Paisley",
    "years": "1974\u20131983",
    "seasons": 9,
    "trophies": 20,
    "avgPosition": 1.5,
    "winRate": "57.4%",
    "trophiesList": [
      "First Division Title (1976, 1977, 1979, 1980, 1982, 1983)",
      "European Cup (1977, 1978, 1981)",
      "League Cup (1981, 1982, 1983)",
      "UEFA Cup (1976)",
      "UEFA Super Cup (1977)",
      "Community Shield (1974, 1976, 1977, 1979, 1980, 1982)"
    ],
    "description": "The most successful manager in British football history. Won 20 major trophies in just 9 seasons, including three European Cups and six League championships."
  },
  {
    "name": "Joe Fagan",
    "years": "1983\u20131985",
    "seasons": 2,
    "trophies": 3,
    "avgPosition": 1.5,
    "winRate": "54.2%",
    "trophiesList": [
      "First Division Title (1984)",
      "European Cup (1984)",
      "League Cup (1984)"
    ],
    "description": "Achieved a historic treble in his debut season (League, European Cup, and League Cup) before retiring after the Heysel tragedy."
  },
  {
    "name": "Kenny Dalglish",
    "years": "1985\u20131991",
    "seasons": 5.5,
    "trophies": 10,
    "avgPosition": 1.5,
    "winRate": "60.6%",
    "trophiesList": [
      "First Division Title (1986, 1988, 1990)",
      "FA Cup (1986, 1989)",
      "Community Shield (1986, 1988, 1989, 1990)",
      "Football League Super Cup (1986)"
    ],
    "description": "Became player-manager and won the Domestic Double in 1986. Guided the club through the dark aftermath of the Hillsborough disaster before resigning in 1991."
  },
  {
    "name": "Graeme Souness",
    "years": "1991\u20131994",
    "seasons": 2.8,
    "trophies": 1,
    "avgPosition": 6.0,
    "winRate": "44.0%",
    "trophiesList": [
      "FA Cup (1992)"
    ],
    "description": "A legendary captain who returned as manager, winning the 1992 FA Cup during a period of transition in the early Premier League era."
  },
  {
    "name": "Roy Evans",
    "years": "1994\u20131998",
    "seasons": 4.5,
    "trophies": 1,
    "avgPosition": 4.0,
    "winRate": "50.4%",
    "trophiesList": [
      "League Cup (1995)"
    ],
    "description": "The final member of the original Boot Room. Restored beautiful attacking play and won the 1995 League Cup with the 'Spice Boys' generation."
  },
  {
    "name": "G\u00e9rard Houllier",
    "years": "1998\u20132004",
    "seasons": 5.5,
    "trophies": 6,
    "avgPosition": 3.8,
    "winRate": "52.0%",
    "trophiesList": [
      "FA Cup (2001)",
      "League Cup (2001, 2003)",
      "UEFA Cup (2001)",
      "Community Shield (2001)",
      "UEFA Super Cup (2001)"
    ],
    "description": "Laid the foundation for Liverpool's 21st-century resurgence, winning a historic cup treble in 2000-01 and instilling modern training methods."
  },
  {
    "name": "Rafael Ben\u00edtez",
    "years": "2004\u20132010",
    "seasons": 6,
    "trophies": 4,
    "avgPosition": 4.0,
    "winRate": "55.4%",
    "trophiesList": [
      "Champions League (2005)",
      "FA Cup (2006)",
      "UEFA Super Cup (2005)",
      "Community Shield (2006)"
    ],
    "description": "A tactical mastermind who led the club to two Champions League finals, securing the historic 2005 Istanbul title and mounting a strong league challenge in 2008-09."
  },
  {
    "name": "Roy Hodgson",
    "years": "2010\u20132011",
    "seasons": 0.5,
    "trophies": 0,
    "avgPosition": 12.0,
    "winRate": "41.9%",
    "trophiesList": [],
    "description": "Managed a highly difficult and brief transitional period during the club's ownership crisis before parting ways in January 2011."
  },
  {
    "name": "Kenny Dalglish (2nd)",
    "years": "2011\u20132012",
    "seasons": 1.5,
    "trophies": 1,
    "avgPosition": 7.0,
    "winRate": "46.2%",
    "trophiesList": [
      "League Cup (2012)"
    ],
    "description": "The club legend returned to steady the ship, winning the 2012 League Cup and reaching the FA Cup Final, while signing key players like Luis Su\u00e1rez."
  },
  {
    "name": "Brendan Rodgers",
    "years": "2012\u20132015",
    "seasons": 3.2,
    "trophies": 0,
    "avgPosition": 5.0,
    "winRate": "51.2%",
    "trophiesList": [],
    "description": "Brought an attractive, high-scoring attacking philosophy that came within inches of winning the Premier League title in 2013-14."
  },
  {
    "name": "J\u00fcrgen Klopp",
    "years": "2015\u20132024",
    "seasons": 9,
    "trophies": 8,
    "avgPosition": 3.3,
    "winRate": "60.9%",
    "trophiesList": [
      "Premier League (2020)",
      "Champions League (2019)",
      "FA Cup (2022)",
      "League Cup (2022, 2024)",
      "UEFA Super Cup (2019)",
      "Club World Cup (2019)",
      "Community Shield (2022)"
    ],
    "description": "Restored Liverpool to the absolute pinnacle of world football. Klopp built a legendary side that won every major trophy available, introducing 'Gegenpressing' and emotional connection."
  },
  {
    "name": "Arne Slot",
    "years": "2024\u20132026",
    "seasons": 2,
    "trophies": 1,
    "avgPosition": 3.0,
    "winRate": "55.3%",
    "trophiesList": [
      "Premier League (2025)"
    ],
    "description": "Achieved immediate success post-Klopp, winning the 2024-25 Premier League title in his debut season and maintaining elite level play in Europe."
  }
];

const legendaryPlayers = [
  { id: "alisson", name: "Alisson Becker", position: "GK", years: "2018–Present", rating: 92 },
  { id: "reina", name: "Pepe Reina", position: "GK", years: "2005–2013", rating: 86 },
  { id: "dudek", name: "Jerzy Dudek", position: "GK", years: "2001–2007", rating: 83 },
  
  { id: "vandijk", name: "Virgil van Dijk", position: "DF", years: "2018–Present", rating: 94 },
  { id: "carragher", name: "Jamie Carragher", position: "DF", years: "1996–2013", rating: 88 },
  { id: "hyypia", name: "Sami Hyypiä", position: "DF", years: "1999–2009", rating: 87 },
  { id: "trent", name: "Trent Alexander-Arnold", position: "DF", years: "2016–Present", rating: 90 },
  { id: "robertson", name: "Andy Robertson", position: "DF", years: "2017–2026", rating: 89 },
  { id: "matip", name: "Joel Matip", position: "DF", years: "2016–2024", rating: 85 },
  { id: "riise", name: "John Arne Riise", position: "DF", years: "2001–2008", rating: 84 },
  { id: "agger", name: "Daniel Agger", position: "DF", years: "2006–2014", rating: 84 },
  
  { id: "gerrard", name: "Steven Gerrard", position: "MF", years: "1998–2015", rating: 96 },
  { id: "alonso", name: "Xabi Alonso", position: "MF", years: "2004–2009", rating: 90 },
  { id: "mascherano", name: "Javier Mascherano", position: "MF", years: "2007–2010", rating: 87 },
  { id: "henderson", name: "Jordan Henderson", position: "MF", years: "2011–2023", rating: 85 },
  { id: "fabinho", name: "Fabinho", position: "MF", years: "2018–2023", rating: 88 },
  { id: "wijnaldum", name: "Gini Wijnaldum", position: "MF", years: "2016–2021", rating: 86 },
  { id: "hamann", name: "Dietmar Hamann", position: "MF", years: "1999–2006", rating: 83 },
  { id: "milner", name: "James Milner", position: "MF", years: "2015–2023", rating: 84 },
  
  { id: "salah", name: "Mohamed Salah", position: "FW", years: "2017–2026", rating: 95 },
  { id: "suarez", name: "Luis Suárez", position: "FW", years: "2011–2014", rating: 94 },
  { id: "torres", name: "Fernando Torres", position: "FW", years: "2007–2011", rating: 91 },
  { id: "mane", name: "Sadio Mané", position: "FW", years: "2016–2022", rating: 91 },
  { id: "firmino", name: "Roberto Firmino", position: "FW", years: "2015–2023", rating: 88 },
  { id: "owen", name: "Michael Owen", position: "FW", years: "1996–2004", rating: 89 },
  { id: "fowler", name: "Robbie Fowler", position: "FW", years: "1993–2001, 2006–2007", rating: 85 },
  { id: "kuyt", name: "Dirk Kuyt", position: "FW", years: "2006–2012", rating: 84 }
];
